### ISSUE TITLE
以公司搜尋工時資訊 API更新 (/workings/search-and-group/by-company)

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#103]
跟據9/4的討論，以公司搜尋工時資訊API需更新:

Input: company name or company id 
Output:
以 (company_name, company_id) 為一個group的id
1. 回傳該group的 「加班是否有加班費」、「加班費是否合法」、「是否有補休」的計數資訊 (資料數>=5者再顯示?
2. 回傳該group，一筆一筆的工時資訊，其中每一筆的工時資訊，除了「加班是否有加班費」、「加班費是否合法」、「是否有補休」的欄位外，都回傳。

Output format: 
```
[
    { 
        "_id":{"name":"聯發科"},
        //if number of data < 5, then there won't be these 3 fields ("has_overtime_salary_count", ""is_overtime_salary_legal_count", "has_compensatory_dayoff_count")
        "has_overtime_salary_count": {
            "yes": 2,
            "no": 2,
            "don't know": 1
         },
        "is_overtime_salary_legal_count": {
            "yes": 1,
            "no": 1,
            "don't know": 0
         },
         "has_compensatory_dayoff_count": {
            "yes": 2,
            "no": 2,
            "don't know": 1
         }
        },
        "workings": [
            {    
                "job_title":"軟韌體工程師",
                "week_work_times":40,
                "overtime_frequency": 0,
                "day_promised_work_time": 8,
                "day_real_work_time": 8,
                "created_at": "2016-07-20T14:15:44.929Z"
                "sector": "內湖"
            }, {    
                "job_title":"軟體工程師",
                "week_work_times":40,
                "overtime_frequency": 2,
                "day_promised_work_time": 8,
                "day_real_work_time": 10,
                "created_at": "2016-07-19T14:15:44.929Z"
                "sector": "內湖"
            }, 
            ...  //共5筆
         ]
    },
    {
         "_id": {"id":"84149961","name":"聯發科技股份有限公司"},
         "workings":[
             {    
                "job_title":"應用工程師",
                "week_work_times":60,
                "overtime_frequency": 3,
                "day_promised_work_time": 8,
                "day_real_work_time": 10,
                "created_at": "2016-07-21T14:15:44.929Z"
                "sector": "內湖"
            }
         ]
    }
]
```
### sorting order:
1. Groups are sorted by the number of working time data in a group (desending order)
2. Working time data in a group are sorted by timestamp (newest to oldest)

**Comment by barry800414** [comment]
I have tried to make a format, please give comments

**Comment by mark86092** [comment]
```
"overtime": {
  "has_overtime_salary": {
    "yes": 2,
    "no": 2,
    "don't know": 1
  },
  "is_overtime_salary_legal": xxx,
  "has_compensatory_dayoff": xxx
}
```

我會建議這樣

**Comment by barry800414** [comment]
That's better, I've update it

**Comment by barry800414** [comment]
@LittleWhiteYA  @mark86092  我有更新格式
然後有幾個建議，一個是如果格式有要修改，盡量在開發前就確定，避免浪費開發者的力氣。開發者& issue的發起者盡可能去看一下格式有沒有問題，先確定下來。

另外，issue上的東西就在issue上討論，不要移到slack上討論，要追溯不太方便。

**Comment by LittleWhiteYA** [comment]
1. 所以 has_compensatory_dayoff_count 這個欄位，不管資料數多少都會統計出來嗎??
2. 我確定一下選填的 undefined 情況
E.g.
                   job_title: "ENGINEER1" , 
                   company: { id: "84149961", name: "COMPANY1" }, 
                   week_work_time: 40,
                   overtime_frequency: 0,
                   day_promised_work_time: 8,
                   day_real_work_time: 8,
                   created_at: new Date("2016-07-21T14:15:44.929Z"),
                   sector: "TAIPEI",

has_overtime_salary
is_overtime_salary_legal,
has_compensatory_dayoff 
以上 3 個是會連 key 都 undefined，跟上面的 E.g. 一樣嗎

**Comment by barry800414** [comment]
1. `has_overtime_salary_count`, `is_overtime_salary_legal_count`, `has_compensatory_dayoff_count` 這三個都是在該group的資料小於5的時候不顯示

2. 第2個問題有點不太懂，上面的E.g.是指?

**Comment by LittleWhiteYA** [comment]
1. 那這 3 個欄位是要回報 has_overtime_salary_count: {}, is_overtime_salary_legal_count: {}, has_compensatory_dayoff_count: {}, 這樣嗎??
2. 
這是一筆使用者資料是會被存成
第一種
{
	job_title: "ENGINEER1" , 
	company: { id: "84149961", name: "COMPANY1" }, 
	week_work_time: 40,
	overtime_frequency: 0,
	day_promised_work_time: 8,
	day_real_work_time: 8,
	created_at: new Date("2016-07-21T14:15:44.929Z"),
	sector: "TAIPEI",
}

第二種
{
	job_title: "ENGINEER1" , 
	company: { id: "84149961", name: "COMPANY1" }, 
	week_work_time: 40,
	overtime_frequency: 0,
	day_promised_work_time: 8,
	day_real_work_time: 8,
	created_at: new Date("2016-07-21T14:15:44.929Z"),
	sector: "TAIPEI",
        has_overtime_salary_count: "",
        is_overtime_salary_legal_count: "",
        has_compensatory_dayoff_count: "",
}

哪一種0.0?

**Comment by barry800414** [comment]
1. 赫然發現我沒有更新好，剛剛更新了!  
應該是連出現都不用出現，像這樣:
```
    {
         "_id": {"id":"84149961","name":"聯發科技股份有限公司"},
         "workings":[
             {    
                "job_title":"應用工程師",
                "week_work_times":60,
                "overtime_frequency": 3,
                "day_promised_work_time": 8,
                "day_real_work_time": 10,
                "created_at": "2016-07-21T14:15:44.929Z"
                "sector": "內湖"
            }
         ]
    }
```

2. 我認為兩種都要能夠處理!

**Comment by mark86092** [comment]
在 Workings collection 裡面不會有 `has_overtime_salary_count: ""` 的情況，只允許 "yes", "no", "don't know", undefined

**Comment by barry800414** [comment]
@mark86092 我指的是，即使前端這樣傳了，也要能夠處理。
出現 `has_overtime_salary_count: ""`的話，依照過去的經驗，應該是插入的時候不會有這個欄位?

**Comment by barry800414** [comment]
愚蠢了，這邊的重點是return什麼資料。 測試資料的部份，可以參考
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L128
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L295 ~ L315

@LittleWhiteYA 你餵哪一種資料應該都可以，最後都不會塞到DB裡面。
