### ISSUE TITLE
Need to run mongo 3.x in travis

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#106]
The mongodb version in travis is now 2.4.x

Need to upgrade to 3.x (or at least 2.6.x)

**Comment by barry800414** [comment]
current mongod version: 3.0.12 (MMAPv1)

**Comment by barry800414** [comment]
I found two possible solution on Internet, but I don't know how to test it.
https://github.com/travis-ci/travis-ci/issues/3694
https://github.com/simon-p-r/json-schema-models/blob/master/.travis.yml

**Comment by mark86092** [comment]
Please send a PR to test it, thanks

**Comment by LittleWhiteYA** [comment]
I follow @barry800414 's solution and done!!

**Comment by barry800414** [comment]
正準備要寫， @LittleWhiteYA 捷足先登XD
不過我寫了一個test去測DB version。
然後我在想update DB version的這個部份要不要另外開PR?  放在API的PR內好像怪怪的

testDBVersion.js
```
var MongoClient = require('mongodb').MongoClient
const assert = require('chai').assert;

describe('Mongo DB version', function() {
    it('should be at least 3.x.x', function(done) {
    	var conn = MongoClient.connect(process.env.MONGODB_URI, function(err, db) {
		    var adminDb = db.admin();
		    adminDb.serverStatus(function(err, info) {
		        var version = parseInt(info.version.split('.')[0]);
		        assert.isAtLeast(version, 3, 'current version is ' + info.version);
		        done();
		    })
		})
    })
})
```

**Comment by LittleWhiteYA** [comment]
哈哈哈哈  好像蠻短的就寫了一下XD
我也覺得好像另外開 PR 比較好
不然你丟 PR
我把那個 commit 刪了
