### ISSUE TITLE
GET /search-and-group/by-job-title  測試有誤

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#117]
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/test/testWorkings.js#L1226

這個測試的目的是測 搜尋 `ENGINEER`，會找到 `ENGINEER1` & `ENGINEER2`。
但因為 `ENGINEER1` & `ENGINEER2` 的資料數量相同，並不會知道哪一個在前，哪一個在後。
這個測試「本身」就有模糊空間，測試的時候有可能會對、有可能會錯。  
建議移除一邊的資料一筆。

@LittleWhiteYA 

此外，建議把_id列入第二個排序考量。

**Comment by mark86092** [comment]
我們最終運行環境是 Linux, mongo3, nodejs 6，這個應該不用太 care

**Comment by barry800414** [comment]
不是阿，即使是 Linux, mongo3, nodejs 6 這個測試本身就有ambiguity
還是有哪邊寫說當排序順序相同的時候，會如何決定排序嗎?

**Comment by mark86092** [comment]
Here: https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L649

**Comment by barry800414** [comment]
那個是group內部的排序吧?
我指的是group本身的排序:
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L673

**Comment by mark86092** [comment]
> 因為ENGINEER1 & ENGINEER2的資料數量相同 

所以最後一步的 sort: created_at: -1 應該不是關鍵，這樣就是 group 內部排序的問題（只是是哪一步）

麻煩交叉測試一下是哪一塊的問題，或是更多的測試狀況（on win），才有辦法定位

**Comment by barry800414** [comment]
我不是說sort: created_at: -1這裡有問題

是這個測試: 
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/test/testWorkings.js#L1226

> L1232                    assert.deepPropertyVal(res.body, '0._id', 'ENGINEER1');
> L1233                    assert.deepPropertyVal(res.body, '1._id', 'ENGINEER2');

它預期了第1個會是ENGINEER1, 第2個是ENGINEER2

可是，如果看上面的data L1085~L1183，會發現職稱為ENGINEER1、ENGINEER2的都是三筆資料，再根據程式碼指定的排序方式 https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L673
應該是根據資料數量。  所以，除非mongodb有講明排序順位一樣的時候，是如何排的，要不然它就可以亂排。那就不該預期「第1個會是ENGINEER1, 第2個是ENGINEER2 」

**Comment by mark86092** [comment]
> 除非mongodb有講明排序順位一樣的時候，是如何排的，要不然它就可以亂排。

所以，就是因為 $group 吐資料出來給 $sort: created_at 有它自己的"排法"，才導致下一步 $sort 沒處理，而 win 與 linux 上結果不同

所以，$group 怎麼排，才會有預設的情況，在底下的連結有說明 https://docs.mongodb.com/manual/reference/operator/aggregation/group/

根據連結，就是 `$sort: {created_at: -1}` 需要改成
```
$sort: {created_at: -1, _id: 1} 
```

**Comment by LittleWhiteYA** [comment]
應該要改的地方在
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L673
''' $sort: { count: -1,} '''
改成
'''$sort: { count: -1, _id: 1} '''
