### ISSUE TITLE
上傳薪時資訊 增加 薪資相關欄位、工作類型欄位

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#125]
Based on: https://projects.invisionapp.com/share/DT950QBRY#/screens/201097338_Index-02

# 原本的欄位: 

原本前端ajax的範例:
```
{
    company_id: xxx,
    company_query: xxx,
    job_title: xxx,
    sector: xxx,
    day_promised_work_time: xxx,
    day_real_work_time: xxx,
    week_work_time: xxx,
    overtime_frequency: xxx,
    has_overtime_salary: xxx,
    is_overtime_salary_legal: xxx,
    has_compensatory_dayoff: xxx,
    email: xxx,
}
```
儲存到DB的格式: 
```
{
    "company": {
        "id": "34051920",
        "name": "OOO工業股份有限公司"
    },
    "job_title": "軟體設計工程師",
    "week_work_time": 40.5,
    "overtime_frequency": 2,
    "day_promised_work_time": 8,
    "day_real_work_time": 10,
    "sector": "XX",
    "has_overtime_salary": "no",
    "has_compensatory_dayoff": "no",
    "query": "OOO工業股份有限公司"
}
```

# 新增欄位 

- 是否在職: `is_currently_employed`
  可能的outcome: {“yes”, ”no”`}

- 離職時間: `job_ending_time_year`, `job_ending_time_month`   (皆為整數字串)
`job_ending_time_year` 要大於等於留下資料的時間的10年前
意即  `job_ending_time_year  >= current_year - 10`，假如今年是2016年，那留2005年的就不行
注意 `job_ending_time_month` 從1開始 (一月)

- 職務型態: `employment_type` 
 可能的內容 = `{ "full-time", "part-time", "intern", "temporary", "contract", "dispatched-labor" }`

- 性別 `gender = { "male", "female", "other" }`   *選填，所以可能沒有這欄位
- 薪資: `salary_type`, `salary_amount`
`salary_type`可能的outcome = `{"year", "month", "day", "hour"} `  
`salary_amount`為整數字串，整數值大於等於0

- 相關職務工作經歷: `experience_in_year`
  `experience_in_year`為整數字串，整數值大於等於0，小於等於50

新的前端ajax範例: 
```
{
    company_id: xxx,
    company_query: xxx,
    job_title: xxx,
    sector: xxx,
    day_promised_work_time: xxx,
    day_real_work_time: xxx,
    week_work_time: xxx,
    overtime_frequency: xxx,
    has_overtime_salary: xxx,
    is_overtime_salary_legal: xxx,
    has_compensatory_dayoff: xxx,
    email: xxx,

    is_currently_employed: xxx,
    job_ending_time_year: xxx, 
    job_ending_time_month: xxx,
    employment_type: xxx, 
    gender: xxx, 
    salary_type: xxx, 
    salary_amount: xxx,
    experience_in_year: xxx, 
}
```

存到DB裡面的格式
- 是否在職: `is_currently_employed` (字串)
  可能的outcome: {“yes”, ”no”`}
- 離職時間: `job_ending_time = { year: 2016, month: 10 }`   (皆為整數)

- 職務型態: `employment_type`   (字串)
 可能的內容 = `{ "full-time", "part-time", "intern", "temporary", "contract", "dispatched-labor" }`

- 性別 `gender = { "male", "female", "other" }`   *選填，所以可能沒有這欄位  (字串)

- 薪資: `salary` = { type: "month", amount: 22000 } 
`salary.type` 為字串
`salary.amount` 為整數

- 相關職務工作經歷: `experience_in_year`
  `experience_in_year`為整數

- 資料時間或離職時間 `data_time = { year: 2016, month: 10 }` 
`data_time.year`: 為整數
`data_time.month`: 為整數，且從1開始計算，1代表1月
當 `is_currrently_employed = 'yes'或未給定`，`data_time`為 `created_at`的年月，當`is_currrently_employed = 'no'`，`data_time` 為 `job_ending_time`

存到DB的範例
```
{
    job_title: "ENGINEER1",
    company: {id: "84149961", name: "COMPANY1" },
    week_work_time: 40,
    overtime_frequency: 0,
    day_promised_work_time: 8,
    day_real_work_time: 8,
    created_at: new Date("2016-07-21T14:15:44.929Z"),
    sector: "TAIPEI",
    has_overtime_salary: "yes",
    is_overtime_salary_legal: "yes",
    has_compensatory_dayoff: "yes",

    is_currently_employed: "no",
    job_ending_time: { year: 2016, month: 11},
    employment_type: "full-time",
    gender: "male",
    salary: { type: "month", amount: 22000 },
    experience_in_year: 0,
    data_time = { year: 2016, month: 11 } 
}
```

工時欄位包含: 
  必填: `week_work_time, overtime_frequency, day_promised_work_time, day_real_work_time`
  選填: `has_overtime_salary, is_overtime_salary_legal, has_compensatory_dayoff`

薪資欄位包含:
  必填: `salary, experience_in_year`

資料驗證: 
1. 工時欄位只要有一個欄位有填寫，就認定使用者想填寫，工時必填欄位若沒有填寫則算錯誤。
2. 薪資欄位同工時欄位的邏輯。
3. 薪資欄位&工時欄位，其中一個必須將必填欄位填寫完
4. 若 `is_currently_employed = 'yes'` 則 `job_ending_time` 必須有資料。

**Comment by barry800414** [comment]
@mark86092  @LittleWhiteYA  
This issue is still under discussion, please review it and give your feedbacks.

**Comment by LittleWhiteYA** [comment]
1. 可能的內容 = { "less than 1 year", 1, 2, 3 ... }
小於 1 年要不要就直接設定為 0 ??
不然這樣 type 不同，感覺之後可能會有問題

2. 性別 gender = { "male", "female", "other" } *Optional
會需要性別的原因為何0.0??
是之後方便做分析嗎

**Comment by barry800414** [comment]
1. 我覺得改成0 ok
2. 是的!  不過不會是近期!

**Comment by mark86092** [comment]
current_employment 是問有沒有在職，所以建議改成 `is_employed` （is 開頭，current 去掉，是 data_time 的當下，不一定是現在）

experience_year 建議改成 `experience_in_year` 表示單位是 year

**Comment by barry800414** [comment]
`experience_in_year`  我覺得沒問題
然後我是建議: `current_employment` -> `is_currently_employed`
因為那個題目真的是問現在是否在職

data_time的意涵是: 
1.如果使用者已經離職，那就是離職的那個年月
2.如果使用者未離職，那就是留下資料的那個年月
有點難給它一個很精確的名詞? (e.g. `job_ending_or_data_time` ? )

**Comment by mark86092** [comment]
data_time 我完全沒頭緒

**Comment by barry800414** [comment]
另一種作法是
if `is_currently_employed` = "yes"   => job_ending_time = { year: 2016, month: 10 }
else if `is_currently_employed` = "no" => job_ending_time = undefined

系統上要抓資料時間的時候，根據 `is_currently_employed` 欄位，是'yes'的話就抓 job_ending_time，是'no'的話，抓created_at的時間，轉成一樣的格式。

**Comment by LittleWhiteYA** [comment]
我針對性別的部分比較有點疑問
因為感覺要作分析還很遠，尤其是以"性別"為因素做的分析，那如果現在讓使用者填性別，會不會有可能降低他們的意願??
我主要的考量點是這個0.0

**Comment by barry800414** [comment]
性別是選填的～
當然也可以不要的，我覺得後端可以先開著沒關係

**Comment by barry800414** [comment]
補上更新: https://github.com/goodjoblife/WorkTimeSurvey/issues/362

**Comment by mark86092** [comment]
@LittleWhiteYA 現在我們用的是 `application/x-www-form-urlencoded`，所以來的資料都是字串（目前先這樣）

gender 如果不填，不會送過來，即會取得 undefined

**Comment by barry800414** [comment]
> job_ending_time.year and job_ending_time.month type 會是字串 or 數字??

存進DB要是整數。

> gender 的部分，如果 user 選擇不填的話，會是 other 對吧??

就不用存進去DB喔!

> salary.type 是只有 "year" and "month" 嗎?? salary.amount type 是 string or int ?

{"year", "month", "day", "hour" }
已更新到spec

> experience_in_year 的選項有甚麼，因為我看示意圖是用下拉式選單的，同上會是 string or int?

存到FB要是整數!  從0~50。

**Comment by barry800414** [comment]
Issue修正:
資料時間或離職時間 data_time 直接在存入的時候寫入DB。
需修改的PR為 #131 #132 #133

**Comment by mark86092** [comment]
Solved
