### ISSUE TITLE
查詢工作資訊頁面的後端API更新 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#127]
- [ ] 最新工作資訊 (原最新工時) #131 
- [ ] 以公司查詢工作資訊 #129 
- [ ] 以職稱查詢工作資訊 #130 

@LittleWhiteYA  @xxhomey19  有沒有興趣來開個API  :P

**Comment by LittleWhiteYA** [comment]
XD   使哪方面的 API ??
職稱引擎那塊的嗎

**Comment by barry800414** [comment]
我更新標題&內文了!
是查詢頁面(查詢工作資訊: 薪資&工時)的後端API
