### ISSUE TITLE
上傳薪時資訊 增加 估計時薪 計算

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#144]
## 增加 _估計時薪_ 計算

簡而言之是把 #125  的部分，再多計算一個欄位，以及修改API Path即可

### 新增欄位:

* `estimated_hourly_wage` (float) : 估計的時薪，計算公式如下
1. 當 `salary.type == "hour"`: 不用算，本身就是指標
    `estimated_hourly_wage` = `salary.amount`
2. 當 `salary.type == "day"`: 用日薪/工作日實際工時去算
    `estimated_hourly_wage` = `salary.amount / day_real_work_time`
3. 當 `salary.type == "month"`: 月薪 * 12 / (52 * 每週平均工時 - (12天國假 + 7天特休) * 工作日實際工時) 估算
    `estimated_hourly_wage` = `(salary.amount * 12) / (52 * week_work_time - (12+7) * day_real_work_time)`
4. 當 `salary.type == "year"`: 年薪 / (52 * 每週平均工時 - (12天國假+7天特休) *工作日實際工時) 估算
    `estimated_hourly_wage` = `(salary.amount) / (52 * week_work_time - (12+7) * day_real_work_time)`

有缺任何一項資訊以致無法計算時薪的時候，就不需計算，讓該欄位為undefined即可。

### 存到DB的格式:
```
{
  estimated_hourly_wage: 136.9294605809129,
}
```

**Comment by LittleWhiteYA** [comment]
@barry800414 
當 salary.type == "day" 的時候，只需要 day_real_work_time
當 salary.type == "month" or "year" 的時候，day_real_work_time & week_work_time 才同時需要吧??

**Comment by barry800414** [comment]
對  基本上就是看公式
但 @LittleWhiteYA 你在解這個issue?

**Comment by LittleWhiteYA** [comment]
對呀   蠻簡單的
而且我看你好像不是在做這個吧0.0?
我就順便寫一寫了

**Comment by barry800414** [comment]
我剛開始寫XD 
沒關係就交給你吧

**Comment by LittleWhiteYA** [comment]
哇  還好我有講...
