### ISSUE TITLE
【查詢資訊權限】查詢薪時 & 查詢權限驗證的串接

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#149]
將查詢薪時資訊的功能，與查詢權限驗證的功能串接在一起。
本issue可能outdated，最新版請見 [hackmd link](https://hackmd.io/s/HyAkcrWHx)

- [x] 薪時排行榜 API 重構 (依賴 #135)
- [x] 薪時上傳表單整合（即 API 開始接受 `rec_by `）(依賴 #143)
- [x] 套用 Authentication, Authorization 兩 middleware 至薪時排行榜上(3個查詢)

四個查詢薪時資訊的[API spec](https://hackmd.io/s/HkDFAy1Xl)

### 針對三種API:
1. 單筆薪時資訊: `GET /workings`
    當使用者有查詢權限，則會按照參數回傳資訊
    當使用者沒有查詢權限，則會重設 sort_by="created_at", page=0, limit=10, order="descending"，意即回傳最新的十筆薪時資訊
     
    p.s. 意思是，如果沒有權限，即使打request，sort_by="week_work_time"，也會被改成sort_by="created_at"

2. 以職稱搜尋: `GET /workings/search_by/job_title/group_by/company`
    如果使用者有權限，那就依照原本的request回應respone
    如果使用者沒有權限，response的 status code: 403

3. 以公司搜尋: `GET /workings/search_by/company/group_by/company`
    如果使用者有權限，那就依照原本的request回應respone
    如果使用者沒有權限，response的 status code: 403

詳見 [API doc](https://github.com/goodjoblife/WorkTimeSurvey-backend/wiki/API-Endpoint-3.x#get-%E5%8F%83%E6%95%B8)

###### tags: `查詢資訊權限`

**Comment by barry800414** [comment]
> 薪時上傳表單整合（即 API 開始接受 rec_by）(依賴 #143)
這一個應該就是 #143 ?

**Comment by mark86092** [comment]
對，上面兩個是這個 issue 的依賴關係

**Comment by mark86092** [comment]
最新工時: `GET /workings` 跟 工時、時薪排行榜: `GET /workings?sort_by=xxx` 這兩者差在哪？

**Comment by barry800414** [comment]
@mark86092 兩個是用同組API，但是在前端介面的地方，會有不同的按鈕可以按喔

我之所以分開寫，是想說沒有權限的話，只能看最新的十筆，工時、時薪的排行不能看

**Comment by mark86092** [comment]
那後者 "工時、時薪的排行" 的 sort_by 是 required or optional ？

**Comment by barry800414** [comment]
是optional，看起來API doc真的超級重要
issue上的資訊也已經outdated
