### ISSUE TITLE
查詢薪時資訊 撰寫測試

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#151]
#135 那邊將測試先暫停，這些測試可分開寫

- [x] 測試最新薪時資訊 (#156)
- [x] 測試 search_by/company/group_by/company (#161)
- [x] 測試 search_by/job_title/group_by/company (#159)

**Comment by barry800414** [comment]
這個issue有點不太懂，先暫停的原因是?

**Comment by mark86092** [comment]
是因為要讓 PR 先合併，方便後續的東西，所以另外開一區補測試

**Comment by mark86092** [comment]
Done
