### ISSUE TITLE
【查詢資訊權限】 使用者查詢資訊權限 API

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#157]
【查詢資訊權限】 使用者查詢資訊權限 API
===
獨立的一個API，讓使用者可以確認使否有查詢資訊的權限。
本issue有可能outdated，最新版請見: [Hackmd link](https://hackmd.io/s/HJ28Exzrx)

### Endpoint
`GET /me/permissions/search`

### Request parameters
| field |explanation|
|:------|-----------|
|`access_token`|從Facebook Login SDK取得的token|

### Response (status_code = 200)
| field |path|explanation|
|:------|----|-----------|
|`hasSearchPermission`|.|該名使用者是否有查詢資訊的權限。可能的值 {`true`, `false`} |

### 實作
將 https://hackmd.io/s/rJ_l8ZeXl 所實作的Middleware串接起來即可。

###### tags: `查詢資訊權限` `API`

**Comment by LittleWhiteYA** [comment]
想問一下
在 Authentication Middleware 的部分
最後是會得到 req.facebook = account 對嗎
但是在 Authorization Middleware 那邊
寫法是拿到 req.user_id
這邊的 user_id 是 req.facebook 的 id or name ?

**Comment by barry800414** [comment]
1. output:  
```
req.user = {
    id:xxx
    type: xxx
} 
```

2. yes，在access_token有給定&伺服器沒有發生錯誤的情況下，status_code應該要是200。回傳true or false沒錯。

**Comment by LittleWhiteYA** [comment]
@barry800414 我有個問題
如果這個 API 也是要傳入 access_token 的話
是不是應該也改成 POST 而不是 GET 阿??

**Comment by mark86092** [comment]
Done
