### ISSUE TITLE
POST /work_experiences 上傳工作經驗API

### ISSUE THREAD

**Issue by h091237557** [goodjoblife/WorkTimeSurvey-backend#190]
[API doc](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=952539904293399&h2=%E4%B8%8A%E5%82%B3%E5%B7%A5%E4%BD%9C%E7%B6%93%E9%A9%97-API)
[DB spec](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=834866527990192&h2=%E9%9D%A2%E8%A9%A6%E5%8F%8A%E5%B7%A5%E4%BD%9C%E7%B6%93%E9%A9%97%E5%88%86%E4%BA%AB-Collection-%E8%A8%AD%E8%A8%88)

data_time資料庫欄位要處理。

```
data_time  欄位須由後端自行根據  is_currently_employed , created_at , job_ending_time ，非由使用者上傳。
```

* [x] Validation
* [x] 儲存到 DB
* [x] Test

**Comment by mark86092** [comment]
我更新了大 block

**Comment by h091237557** [comment]
奇怪~我著麼完全沒印象我有開這個issue.... XD

**Comment by h091237557** [comment]
data_time資料庫欄位要處理。

```
data_time  欄位須由後端自行根據  is_currently_employed , created_at , job_ending_time ，非由使用者上傳。
```

**Comment by h091237557** [comment]
#292 #294 
(P.s Pr這個以後也打在裡面 )

**Comment by mark86092** [comment]
Done
