### ISSUE TITLE
DELETE /replies/:id/likes 移除留言的讚 API

### ISSUE THREAD

**Issue by h091237557** [goodjoblife/WorkTimeSurvey-backend#197]
[API doc](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=429666923557032&h2=%E5%8F%96%E6%B6%88%E7%95%99%E8%A8%80%E7%9A%84%E8%AE%9A-API)

**Comment by barry800414** [comment]
本API有修改，後端實現方式不同
請見：https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=245471885857138&h2=%E7%95%99%E8%A8%80%E6%8C%89%E8%AE%9A-Collection-%E8%A8%AD%E8%A8%88

**Comment by h091237557** [comment]
#315

**Comment by mark86092** [comment]
Done
