### ISSUE TITLE
DELETE /experiences/:id/likes 移除單篇經驗的讚 API

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#200]
[API doc](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=858100105206540&h2=%E5%8F%96%E6%B6%88%E5%96%AE%E7%AF%87%E6%96%87%E7%AB%A0%E7%9A%84%E8%AE%9A-API)

這邊要修改兩個東西
1. 更新reply的like_count數量(減1)。
2. 將reply_likes的資料刪除。

**Comment by h091237557** [comment]
這邊要修改兩個東西
1. 更新reply的like_count數量(減1)。
2. 將reply_likes的資料刪除。

**Comment by h091237557** [comment]
#290

**Comment by mark86092** [comment]
感謝 close 它
