### ISSUE TITLE
services & routing 層規劃

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#204]
### file structure:
```
./services
    - experience_service.js
    - reply_service.js
    - like_service.js
./routes
    ./experiences
        - index.js
        - replies.js
        - likes.js
    ./replies
        - index.js
        - likes.js 
    - interview_experiences.js 
    - work_experiences.js
```

### services 規劃 (最小規劃)
`experience_service.js` 的 services 
* checkExperienceIdExist()
* createWorkExperience()
* createInterviewExperience()

`reply_service.js` 的 services
* checkReplyIdExist()
* createReply()

`like_service.js` 的 services
* createLikeToReply()
* deleteLikeToReply()
* createLikeToExperience()
* deleteLikeToExperience()

### routing 規劃
`experiences.js` 負責的routing
* `GET /experiences/:id`
* `GET /experiences`

`interview_experiences.js` 負責的routing
* `POST /interview_experiences/`

`work_experiences.js` 負責的routing
* `POST /work_experiences/`

`replies.js` 負責的routing
* `POST /experiences/:id/replies`
* `GET /experiences/:id/replies`

`likes.js` 負責的routing
* `POST /experiences/:id/likes`
* `DELETE /experiences/:id/likes`
* `POST /replies/:id/likes`
* `DELETE /replies/:id/likes`

sample code:
![pasted_image_at_2017_03_30_08_40_pm](https://cloud.githubusercontent.com/assets/3805975/24507138/3dc9915e-1592-11e7-8f82-2625a0f0659f.png)

**Comment by mark86092** [comment]
幾個建議：

1. `experience_services.js` 是代表裡面會有多個嗎？
2.想問 replies.js / likes.js 是什麼原因特別獨立？而不是放在 experiences / replies 的資料夾內

**Comment by barry800414** [comment]
> 1. experience_services.js 是代表裡面會有多個嗎？

多個是指?  
我是覺得裡面有很多服務(function)，不過要想成只有一個class用單數也行，這個我沒差

> 想問 replies.js / likes.js 是什麼原因特別獨立？而不是放在 experiences / replies 的資料夾內

我是prefer以功能去區分檔案，點讚的功能放到experiences / replies 覺得滿怪的。

**Comment by mark86092** [comment]
> 多個是指?

我也不知道多個什麼，我是看到複數所以直接問了，你應該有考量

> 點讚的功能放到experiences / replies 覺得滿怪的。

我的意思是放到 `./routes/experiences/replies.js` 的意思，覺的有符合對 經驗做留言處理 的功能

**Comment by h091237557** [comment]
1. 通常都是用單數~ 
2.  如果是route，這樣合理~ 的確符合這意思~

**Comment by barry800414** [comment]
> 我的意思是放到 ./routes/experiences/replies.js 的意思，覺的有符合對 經驗做留言處理 的功能

我剛在想這個，如果要限縮留言的功能在經驗分享這件事情上，這樣做OK。
但如果留言是一個general的功能，譬如小教室之後也有留言功能，或者之後有什麼閒聊區，可以隨便打想講的內容，下面也有要留言，那放到裡面就有點奇怪。
(但是，如果要是個general功能，欄位就不是放experience_id了，應該也會改成DBRef)

**Comment by h091237557** [comment]
這樣的話，同常會在service/replies裡面，用不同的方法來來進行，route只是會呼叫不同的方法而以
Ex. 
```
function createExpererenceReply(){
  _createReply()
}

function createClassroom Reply(){
   _createReply()
}

function _createReply(){

}
```

**Comment by barry800414** [comment]
1. 我改單數
2. 我剛想到，如果把「讚」想成general的功能，其實不用這樣四組:
```
createLikeToReply()
deleteLikeToReply()
createLikeToExperience()
deleteLikeToExperience()
```
可以是兩組:
```
createLike()
deleteLike()
```
裡面接collection name + 該collection裡面的document id，就可以了
要對經驗分享按讚就 createLike(`experiences`, 'some_exp_id') 
要對留言按讚就 createLike(`replies`, 'some_reply_id')

**Comment by mark86092** [comment]
看起來說法一致，不過如果我是 call 的人，我會比較想用 

```
createLikeToReply()
deleteLikeToReply()
```

反而是  `createLike(experiences, $id, ...)` 會用的怕怕，怕打錯字或什麼的

**Comment by mark86092** [comment]
BTW, service 的放法與 routes 的放法應該可以分開討論

**Comment by h091237557** [comment]
同意樓上，雖然下面是有四種方法。
```
createLikeToReply()
deleteLikeToReply()
createLikeToExperience()
deleteLikeToExperience()
```
但是實際上的程式碼應該是裡面還會在包一層，通用的。

```
function createLikeToXXXReply(){
  _createLike("xxx")
}

function createLikeToExperience Reply(){
   _createLike("experience")
}

function _createReply(){

}
```

**Comment by barry800414** [comment]
那 `likes.js`  `replies.js` 這類的要放在 `experiences` 底下嗎?

**Comment by h091237557** [comment]
Route :可以放在experiences  底下。
Service : 不用。

**Comment by barry800414** [comment]
這個你們可以直接修，我今天在外面，要晚上才有辦法改

**Comment by h091237557** [comment]
這邊我來修好了~運氣好的話，今天我會送pr，這版就是符合這架構。的版本
