### ISSUE TITLE
建立code coverage環境

### ISSUE THREAD

**Issue by h091237557** [goodjoblife/WorkTimeSurvey-backend#218]
在github上面使用coveralls，它和ci一樣每次上傳時，都會執行一次code coverage，然後會有標籤給我們丟到readme上面。

[https://coveralls.io/](https://coveralls.io/)

P.S 我用Istanbul測試，咱們的測試覆蓋率為70%左右。
[https://github.com/gotwarlost/istanbul](https://github.com/gotwarlost/istanbul)

這個issue閒時在用吧。

**Comment by mark86092** [comment]
能麻煩 @h091237557 設置一下嗎？

**Comment by h091237557** [comment]
ok~

**Comment by h091237557** [comment]
#255
