### ISSUE TITLE
POST的時候，email欄位沒有成功上傳

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#230]
剛剛在更新發信系統的email list，發現很奇怪，自從mail list長到800多筆後就沒有再增加了，但我們應該有5000筆資料，最近成長很多才對，仔細檢查發現後面的資料都沒有email，然後就發現後端有ＢＵＧ了

打錯字啊！！！

https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings_post.js#L21

**Comment by mark86092** [comment]
趕快送一個 Fix, 與 Test

**Comment by mark86092** [comment]
已修正，以後要把重要的 API 完整的測試

**Comment by h091237557** [comment]
那這樣我覺得 #218 這個可以移到早點作，它可以檢查我們程式碼中那些有測試到，那些沒測試到。

**Comment by mark86092** [comment]
#218 我覺得ＯＫ，不過我搞不懂它怎麼算出來的

**Comment by h091237557** [comment]
應該是這樣算~如下範例的話，它只有測試到if(isX)，那他的code coverge 應該是只有50%，因為else沒算到。
```
function aa(isX){
   if (isX){
     ....
   }else{
     ....
   }
}

it(' aa function test'){
   aa(true);
}
```
