### ISSUE TITLE
[3.x] 隱藏排序後前 1% 的資料

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#243]
See https://github.com/goodjoblife/WorkTimeSurvey/issues/479

後端我想做成拿取第 n 頁時，會 skip 1% 的數量，
剩下的 1% 則是另外的 API 拿取

**Comment by barry800414** [comment]
這個就依照之前線上會議的想法。
再新增兩支API，一支是只會拿到前1%的資料，另外一支則是從第1%後的那一筆開始拿資料。

**Comment by barry800414** [comment]
這件事後來是交給 @LittleWhiteYA 喔，我改assignee了

**Comment by mark86092** [comment]
今晚我會拿回來做

**Comment by mark86092** [comment]
今天有想到一個選項：

提供一個參數，讓 API 可以 skip 前 1% 的數量或維持原本行為

這樣在瀏覽時薪排行榜時，預設會看到 1% 的資料被跳過（會有提示字）

例如：

![image](https://cloud.githubusercontent.com/assets/1908007/26591197/71684528-458f-11e7-8879-69e81082c070.png)

使用者可以選擇打開，而重新讀出沒有 skip 前 1% 的資料

**Comment by barry800414** [comment]
不太懂，可以說得更具體一點嗎？
request 的參數多加了什麼？ 加了會有什麼差別？

**Comment by mark86092** [comment]
多一個參數（參數名未定），當 request 提供這個參數時，會 skip 前 1% 的數量當作回傳的薪時

若沒有提供這個參數，與原本一樣

**Comment by barry800414** [comment]
這樣的做法，1%之後的資料取得沒有問題。
不過，使用者如果想要取得前1%的資料，要怎麼取得？  先打一個request知道總共有幾筆資料嗎？

**Comment by mark86092** [comment]
我想要的是：當使用者指定想看全部的資料時，就會讓頁面刷掉，重新的從頭開始拿資料（並顯示這些資料含有 前1%，統計上可能不真等）
