### ISSUE TITLE
Post /interview_experience (補1 : post資料類形修改)

### ISSUE THREAD

**Issue by h091237557** [goodjoblife/WorkTimeSurvey-backend#249]
決定將這些欄位用 Number
experience_in_year, interview_time.year, interview_time.month, salary.amount, overall_rating

新增資料的話要插入兩個欄位：like_count = 0, reply_count = 0

api文件 : [https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=634290353025355&h2=%E4%B8%8A%E5%82%B3%E9%9D%A2%E8%A9%A6%E7%B6%93%E9%A9%97-API](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=634290353025355&h2=%E4%B8%8A%E5%82%B3%E9%9D%A2%E8%A9%A6%E7%B6%93%E9%A9%97-APIhttps://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=634290353025355&h2=%E4%B8%8A%E5%82%B3%E9%9D%A2%E8%A9%A6%E7%B6%93%E9%A9%97-API)

**Comment by h091237557** [comment]
#234 、 #235

**Comment by mark86092** [comment]
235應該沒關係到
