### ISSUE TITLE
GET /experiences/:id ( 補-多補type為work,多回傳data_time )

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#267]

**Comment by h091237557** [comment]
這邊的data_time要注意，如果有post時有離職的時間，則用它，反之則用留資料時間。

**Comment by h091237557** [comment]
這個iussus可以close掉，因為是在新增工作經驗時要做的，而只要後端DB有存data_time，則api就有回傳data_time。要提醒在新增工作經驗時，data_time要注意，如果有post時有離職的時間，則用它，反之則用留資料時間。

[後端設計書](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=834866527990192&h2=%E9%9D%A2%E8%A9%A6%E5%8F%8A%E5%B7%A5%E4%BD%9C%E7%B6%93%E9%A9%97%E5%88%86%E4%BA%AB-Collection-%E8%A8%AD%E8%A8%88)
