### ISSUE TITLE
GET /experiences 的 limit 參數無作用

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#269]
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/4.x/routes/experiences/index.js#L59

`const limit = req.query.limit || 25;`

當 limit 是 string，或導致 500 錯誤

**Comment by h091237557** [comment]
OK~補測試~

**Comment by h091237557** [comment]
#275 - Fix
