### ISSUE TITLE
Google Recaptcha 後端支援

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#271]
Google Recaptcha 後端這邊的支援非常簡單
1. 在註冊這個服務的時候會拿到兩把 key，一把site key給前端用，一把secret key給後端用，後端這把要保密
2. 前端在使用者回應挑戰(e.g. 扭曲的字）成功或失敗後，可以取得一個response。
3. 前端把這個response往後端送，後端再把response以及secret key以POST 送到 `https://www.google.com/recaptcha/api/siteverify` 即可取得該使用者是否成功完成挑戰。

文件：
https://developers.google.com/recaptcha/docs/verify

這個issue先放到backlog，待檢舉流程確定後再放到todo

**Comment by mark86092** [comment]
我猜你說的是 v2

幾個問題可以之後想想：

1. "開發"的時候，前端後端要怎麼測試，這裡的 site ke, secret key 是一組的，怎麼搭配運作？(localhost等問題)
2. 怎麼寫測試
3. 這個支援寫成 Libs 或是 middleware 或是？

**Comment by barry800414** [comment]
版本有三種：
1. Recaptcha v2 （主要的版本）
2. invisible recpatcha (預設不會先出現widget的版本，當它認為client有嫌疑才會跳出來）
3. Recaptcha v1  (已經不支援)

我講的是v2沒錯。

> "開發"的時候，前端後端要怎麼測試，這裡的 site ke, secret key 是一組的，怎麼搭配運作？(localhost等問題)

https://developers.google.com/recaptcha/docs/start 這裡有提到可以把localhost 加入specified domain，方便開發。

> 怎麼寫測試

關於測試的部分，官方有提供一組key方便測試，FAQ的部分有提到：
https://developers.google.com/recaptcha/docs/faq

> 這個支援寫成 Libs 或是 middleware 或是？

目前的想法是middleware，加在新增檢舉的API 前面，沒有過驗證就跳 http error。
不過底層可能有個lib，專門負責跟google recaptcha的server溝通

**Comment by barry800414** [comment]
暫時不需要做 recaptcha 了，先關掉
