### ISSUE TITLE
[dev/3.x] authors collection 轉移成 users collection 規劃

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#276]
1. 建立一個 `users` collection (參考 http://passportjs.org/docs/profile)

```
{
  _id: ObjectId
  id: A unique identifier for the user, as generated by the service provider.
  provider: The provider with which the user authenticated (facebook, twitter, etc.).
  其它欄位
  例如recommendation_string
}
```

2. 將 `authors` 的欄位轉移成新的 `users`
2. 將 `workings` Collection 的 author 欄位換成相對應的 _id
4. 將 `recommendations` 的欄位更新至 `users`

**Comment by barry800414** [comment]
想問一下，哪一些欄位，或者說哪一些欄位組合會是unique的？

**Comment by mark86092** [comment]
`(id, provider)`，但是這個還要仔細想

`recommendation_string` 就必須要是 unique (with partial index，需 mongodb >= 3.2，要確定環境)

**Comment by mark86092** [comment]
更新：

考量到未來我們可能支援多 social account login，`users` 欄位調整成

```
{
  _id,
  [facebook_id] --> (unique, partial index)
  [google_id] --> (unique, partial index)
}
```

這種方法可以讓同個 user 綁定多社群帳戶

**Comment by mark86092** [comment]
mlab 的 MongoDB version 3.2.11

**Comment by barry800414** [comment]
想問一下為什麼要用 partial index?  或者說怎麼用?
我查了一下doc，目前對partial index的理解是只針對特定document ( 會有個filter )建index的機制。
我們要針對哪些doc?

然後我支持
```
{
  _id,
  [facebook_id] --> (unique, partial index)
  [google_id] --> (unique, partial index)
}
``` 
拆成這樣的形式，未來可以多帳號綁定同個user
