### ISSUE TITLE
Create capped collection for 熱門關鍵字

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#279]
- [ ] collection name: `search_by_company_keywords`
- [ ] collection name: `search_by_job_title_keywords`

[doc](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=824457202621407&h2=%E4%BB%A5%E5%85%AC%E5%8F%B8%E6%90%9C%E5%B0%8B%E7%9A%84%E9%97%9C%E9%8D%B5%E5%AD%97-Collection-%E8%A8%AD%E8%A8%88)

先放入backlog

**Comment by mark86092** [comment]
Ref: https://docs.mongodb.com/manual/core/capped-collections/

這裡請評估一下 max 1000 所需要的 size 大約多少？

**Comment by barry800414** [comment]
剛剛做了個實驗，塞了1,000 個 { 'word': 'random string with 20 characters' } 的document，size是 112,000 bytes。塞10000個就是 1120,000 bytes。

實際上存Ｎ個document的Ｎ啊，可以討論一下大概要多大，我目前覺得1000有點太小，可能用5000或10000。

**Comment by LittleWhiteYA** [comment]
這個 issue 是不是完成了？

**Comment by barry800414** [comment]
Yes, I close it
