### ISSUE TITLE
GET /experiences API Patch: 將使用者查詢的詞新增至熱門關鍵字 collection

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#280]
當使用者以公司搜尋，將關鍵字新增至：`search_by_company_keywords`
當使用者以職稱搜尋，將關鍵字新增至： `search_by_job_title_keywords`

**Comment by mark86092** [comment]
這有 bug 需要 patch ?

**Comment by barry800414** [comment]
不算bug，只是提醒要把這件事情做進去

**Comment by barry800414** [comment]
痾，發現跟 #247 重複...
