### ISSUE TITLE
GET /experiences 的 preview補充

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#299]
目前 preview 需要實作進去

**Comment by h091237557** [comment]
` preview`應該是要在 get /experiences 時處理吧，我記得資料庫沒有存這個欄位。然後我有在[這邊]有先簡單寫個`preview`取得，只要在改在那就夠了(https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/4.x/routes/experiences/index.js#L91)

**Comment by mark86092** [comment]
我是看文件上面寫 preview 前 160 字，且還沒 resolve

> ​​整篇內容的preview。前160個字。

如果決定是這樣，那再把文件寫清楚最後的決定

@barry800414 關於文件上面的討論串，需要決定

**Comment by h091237557** [comment]
嗯我那邊只是想暫留位置 ~ 因為這好像一直沒決定好。

**Comment by barry800414** [comment]
這邊確實一直還沒確定，直接給幾個選項，我們來投票好了

1. DB不需新增preview欄位，直接使用第1個section的內容，至多前Ｎ個字
2. DB不需新增preview欄位，擷取第1, 2... 個section的內容，直到滿Ｎ個字
3. POST 時 DB新增preview欄位，內容為第1個section的內容，至多前Ｎ個字。GET時直接取用preview欄位
4. POST 時 DB新增preview欄位，擷取第1, 2... 個section的內容，直到滿Ｎ個字。GET時直接取用preview欄位

**Comment by barry800414** [comment]
Ok，選1，我會去更新document，然後暫定160字。
字數的部分等與前端一起討論。

**Comment by mark86092** [comment]
看起來 1 的話限制 N 個字有點不需要呀，實在想不到有 N 沒 N 差哪

**Comment by barry800414** [comment]
差在，如果一次取得很多篇 (e.g. 現在limit最大可以是100)，而很多人第一段都寫很多的話，就會比較肥大。

**Comment by h091237557** [comment]
#316
