### ISSUE TITLE
測試 POST 的 API 是否可以透過 Authorization Header 認證

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#300]
目前的 Authentication 傳 token 有三種方法：

1. GET 用 網址 ?access_token
2. POST 帶 access_token 在 body 裡
3. 透過 Header `Authorization: Bearer token`

1, 2 在測試裡面都有測試過，

但 3 的情況卻沒做

**Comment by LittleWhiteYA** [comment]
這部分我不是很懂，是否可以透過 Authorization Header 幹嘛??
傳身分認證嗎??

**Comment by mark86092** [comment]
對，標題打斷掉了，我修正

**Comment by mark86092** [comment]
更新 comment 說明

**Comment by h091237557** [comment]
#349
