### ISSUE TITLE
GET /experiences   search_by 欄位是否有預設值

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#304]
目前 API doc 裡面 `search_by` 欄位預設值是 `company`，但目前dev/4.x 上其實沒有預設值。 不給會跳error。

其實覺得不要有預設值比較合理，所以想改API doc，把 search_by 的預設值拿掉。

這個應該可以快速決定，@mark86092  你覺得如何？

**Comment by mark86092** [comment]
其實 code 裡面是有實作的喔

**Comment by h091237557** [comment]
這邊我有處理也　～　
```
  if (search_by == "job_title") {
        query.job_title = new RegExp(lodash.escapeRegExp(search_query.toUpperCase()));
    } else {
        if (search_query) {
            query["$or"] = [{
                'company.name': new RegExp(lodash.escapeRegExp(search_query.toUpperCase())),
            }, {
                'company.id': search_query,
            }];
        }
}
```

**Comment by mark86092** [comment]
讚，正要貼這段

**Comment by h091237557** [comment]
不過我忘了這段有沒有測試到 ~

**Comment by mark86092** [comment]
BTW, @barry800414 `GET /experiences/` 跟 `GET /experiences` 實際上代表不一樣的東西喔，

前者有資料夾的概念，後者不是

**Comment by mark86092** [comment]
> 不過我忘了這段有沒有測試到 ~

我記得有給空的話，是 company

不過這邊的疑問點就是，如果 `search_by=HAHAHA` 這樣還是搜尋 company 嗎？

**Comment by LittleWhiteYA** [comment]
有 default 值我覺得沒關係呀0.0?
不合理的原因是為何??

**Comment by h091237557** [comment]
我記得`search_by=HAHAHA`的話會直接在這被檔。

```
function _isValidSearchByField(search_by) {
    if (!search_by) {
        return true;
    }
    const Default_Field = ["company", "job_title"];
    return Default_Field.includes(search_by);
}
```

**Comment by barry800414** [comment]
不想給default的原因是，要前端自己很確定要用公司搜還是職稱搜。

如果給預設值，比較容易依賴預設值，忘記自己現在是用什麼搜。

**Comment by LittleWhiteYA** [comment]
但是對使用者而言，有預設值這件事應該比較正常吧？

**Comment by barry800414** [comment]
@h091237557 我想問，職稱有預設值的部分，為什麼不要在這邊處理呢？

```
    if (!_isValidSearchByField(req.query.search_by)) {
        next(new HttpError("search by 格式錯誤", 422));
        return;
    }
    const sort_field = req.query.sort || "created_at";
    if (!_isValidSortField(sort_field)) {
        next(new HttpError("sort by 格式錯誤", 422));
        return;
    }
```
意思是用類似     `const sort_field = req.query.sort || "created_at";  ` 的方法

比較一致？

**Comment by mark86092** [comment]
明確比暗示好，所以我覺得可以拿到，讓 search_by 變成必要值（不過請通知相關的修正）

**Comment by mark86092** [comment]
> 我想問，search_by有預設值的部分，為什麼不要在這邊處理呢？

是要另開 issue（code 是對的，所以當然是提案的人要幫忙改囉）？還是單純詢問？

**Comment by barry800414** [comment]
@mark86092  這樣，要不要取消 search_by 預設值，給你決定。幾個人這樣來來回回沒有結論，無法決定。我是覺得要。

然後我是覺得目前處理 search_by 預設值的地方有點隱晦，理解上比較吃力。但不修改也沒差啦。

**Comment by mark86092** [comment]
> 明確比暗示好，所以我覺得可以拿掉

我覺得要，那就定案

> 目前處理 search_by 預設值的地方有點隱晦

不過這個就是加強的部份，不算錯誤，所以盡量送 PR 吧

**Comment by h091237557** [comment]
#311

**Comment by barry800414** [comment]
@mark86092 問一下

> 我覺得要，那就定案

這個的意思是，要有預設值還是沒有預設值？
我的理解是“要拿掉”，不要有預設值

我看 #311 是有預設值的寫法？

**Comment by barry800414** [comment]
OK, 確定了
search_by 不要預設值

**Comment by h091237557** [comment]
#311 Fixed
