### ISSUE TITLE
POST /experiences/:id/replies  report_count 初始化 & 回傳 report_count

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#307]
- [ ] reply_model.js 裡面在新增 reply 的時候，加上 report_count=0 的初始化
- [ ] 成功新增reply 的話，回傳值加上 report_count 

API doc 已經更新

**Comment by mark86092** [comment]
`replies` collection 不會紀錄 reply_count，而是記錄 floor

所以，回傳的 reply 有回傳 reply 的 floor

**Comment by barry800414** [comment]
我打錯字了！！ 是report_count ..

**Comment by mark86092** [comment]
這個也麻煩歸類

![image](https://cloud.githubusercontent.com/assets/1908007/25840017/a19315f8-34cc-11e7-9fc9-790da1cba13c.png)

Project 給開發者照進度分類
Milestone 照需求分類
