### ISSUE TITLE
POST /experiences/:id/replies 新增到DB的欄位應為 author，不是user

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#308]
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/4.x/routes/experiences/replies.js#L13
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/4.x/routes/experiences/replies.js#L32

ref: [DB doc](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy)

**Comment by mark86092** [comment]
這邊有沒有考慮改用 user 的 _id 存？用欄位名 author_id or user_id

**Comment by barry800414** [comment]
詳細裡面要存什麼我還沒仔細看你們的提案，但欄位名稱錯誤，就先開issue了。
會再仔細看你們的提案

**Comment by h091237557** [comment]
#314

**Comment by mark86092** [comment]
Done
