### ISSUE TITLE
Models need tests

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#309]
現在的 models 都是透過 API 測試達到 coverage

不過，比較根本的做法是測試 model 對於各種狀況的反應，最後給出 resolve 與 reject

舉例來說：incrementLikeCount 就可以針對是否正確的 $inc like_count 這個欄位進行不同情形的測試

對於 API 而言，就可以充分 Mock incrementLikeCount

**Comment by h091237557** [comment]
我讚成model層要測試，但不太讚同API層那用mock的，原因如下。

原因 => 
在軟體測試中，包含`單元測試`與`整合測試`，現階段我們的測試為`整合測試`，而如果我們現在將API變成`單元測試`的話，我們就會`缺少了完整串接API層與Model層的測試`，雖然coverage不會有什麼變動，但一定會影響到品質(ex. 我們mock resolve 出的和model resolve出的東西不一樣)。

補 : 單元測試說明 [傳送門](https://dotblogs.com.tw/hatelove/archive/2012/11/05/learning-tdd-in-30-days-day2-unit-testing-introduction.aspx)
補 : 單元與整合的差異[傳送門](http://kojenchieh.pixnet.net/blog/post/75408973-%E6%95%B4%E5%90%88%E6%B8%AC%E8%A9%A6(integation-testing)%E5%92%8C%E5%96%AE%E5%85%83%E6%B8%AC%E8%A9%A6(unit-testing)

建議 => 
所以我這裡建議API層那的整合測試還是繼續留這，不要用mock將它變成單元測試，而model層就是新增model層測試。

補充 =>
在比較巨型軟體開發中，單元測試與整合測試都是兩者都會做的，但我們這裡不建議兩者都寫，因為時間成本會過高。

**Comment by mark86092** [comment]
> 我們mock resolve 出的和model resolve出的東西不一樣

這的確是會讓測試被蒙在鼓裡，不過這是有用到 mock 都會出現的問題（包含 mock 參數太寬、mock 與原本測試的不合）

--

原則上我們還是會先對 API 做整合測試，
至於將 model mock，我這邊可能沒說清楚，的確如你說的，很容易有問題，`對於 API 而言，就可以充分 Mock incrementLikeCount` 這個請把它當作一個小小小舉例

目前在 API 整合測試上，有 mock的有 authentication, authorization, http requests，這三塊是比較常用到的 library，也是會被 refactoring，所以才會做 unit test

> 在比較巨型軟體開發中，單元測試與整合測試都是兩者都會做的，但我們這裡不建議兩者都寫，因為時間成本會過高。

我是這樣想，如果一個 libraray function 被共用的次數過高，就要寫，不然只是把技術債往後拋，然後會造成日後維護負擔更大

**Comment by mark86092** [comment]
BTW, 這裡放 enhancement，代表不急喔，是有的話更好，而且挑重要的測試就好

**Comment by h091237557** [comment]
Ok ~

**Comment by h091237557** [comment]
```
我是這樣想，如果一個 libraray function 被共用的次數過高，就要寫，不然只是把技術債往後拋，然後會造成日後維護負擔更大
```

對了關於你說的這句話是對的，但我並不是說library不做測試，而是還不用做到單元，但至少要做整合，如下面程式碼中，我是覺得還不需要做到像下面單元測試一樣。

```
const likeModel = require('')

//整合 
 it('', function() {
              const like_model = new likeModel();
              return like.model.getLike(id).then((like) => {
                       ......
              })
});

//單元

 it('', function() {
              const like_model = new likeModel();
              sandbox = sinon.sandbox.create();
              sandbox.stub( like_model, 'getLike')
                .withArgs(sinon.match.object)
                .resolves({ _id: 'aaaa', experience_id: 'objectId'});

              return like.model.getLike(id).then((like) => {
                       ......
              })
});

```

**Comment by barry800414** [comment]
這個issue我最快端午連假才會給想法。但我對如何測試比較沒想法，如果你們有結論可以直接做。
