### ISSUE TITLE
GET /experiences 回傳 report_count、測試修改

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#318]
- [ ] 是否要回傳 report_count
- [ ] 測試 Seeding

看不懂麻煩詢問，PR 標準會按照這個

**Comment by barry800414** [comment]
測試seeding看不太懂

**Comment by mark86092** [comment]
在測試裡面建立資料庫的假資料（Database seeding：https://en.wikipedia.org/wiki/Database_seeding）
