### ISSUE TITLE
reports collection 是否要建立 database migration

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#319]

**Comment by barry800414** [comment]
YES

**Comment by barry800414** [comment]
[reference doc](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=346520897234293&h2=%E6%AA%A2%E8%88%89%E8%B3%87%E8%A8%8A-Collection-%E8%A8%AD%E8%A8%88)
