### ISSUE TITLE
[3.x] 以公司搜尋的排行榜 無平均值放置最後

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#321]
這裡包含用"估計時薪"或"一週平均總工時"的排序

**Comment by barry800414** [comment]
剛剛在想一件事，目前我們已經要再新增兩支API了
是單筆薪時資訊以週工時或估計時薪排名的前1% API 和 從1%後開始排序的API

有沒有可能，再新增兩支API
1. 以公司或職稱搜尋的時候，僅顯示有平均值的部分
2. 以公司或職稱搜尋的時候，僅顯示無平均值的部分

前端先用1的API，1讀完後再讀2

**Comment by mark86092** [comment]
> 如果Mongodb沒有query辦法處理無值的情況下要排前面後面的話，勢必是我們對ＤＢ下query後才能操作

是指哪段 query，下query後才能操作，操作什麼？

**Comment by barry800414** [comment]
aggregate裡面做$avg，又做對平均的欄位做排序的情況下。
由小到大排以及由大到小排的這兩種需求，其中如果一定有一種會把平均值為null的欄位排在最前面的話，就很難用mongodb內建的功能去達成我們的需求。

**Comment by mark86092** [comment]
可以參考這裡：https://docs.mongodb.com/manual/reference/operator/aggregation/#aggregation-pipeline-operator-reference

`$match`，不過需要評估點效率

**Comment by LittleWhiteYA** [comment]
`$match` 應該算是 filter 吧？除非 null 的資料不打算顯示不然我覺得應該不能用
我打算用暴力解，直接用 for 把資料在最前面平均值是 null 的拉到最後面
公司 or 職稱搜尋不像單篇薪時搜尋一樣需要翻頁，所以不需要做 2 次 query 就可以解決這問題了

**Comment by mark86092** [comment]
看起來是可行的！
