### ISSUE TITLE
[3.x] 單筆薪時資訊的 估算時薪排行榜（由低到高）

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#322]
原 code 排序的時候有用

```
query = {
  estimated_hourly_wage: {$exists: false},
};
```

不過仍然會出現如圖：
![image](https://cloud.githubusercontent.com/assets/1908007/26164766/4257d6b0-3b60-11e7-960d-4bab92e6df43.png)

經檢查是：`estimated_hourly_wage` 欄位被放上 `null`

這算是一個 Bug

**Comment by mark86092** [comment]
被放上 null 是因為：https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings_post.js#L363

當 return undefined 時，working.estimated_hourly_wage 不該被給值

See #154

**Comment by mark86092** [comment]
麻煩 @barry800414 @LittleWhiteYA 瞭解一下這個狀況

**Comment by barry800414** [comment]
![2017-05-18 10 39 13](https://cloud.githubusercontent.com/assets/3805975/26207701/dbc1daf2-3c1a-11e7-9a95-84f2b011ca5a.png)
確實是這樣沒有錯

**Comment by barry800414** [comment]
測試了一下，object裡面如果有欄位是undefined，進到mongodb會變null。 $exists: true就會判定是存在。

**Comment by barry800414** [comment]
整理一下todo:
- [ ] 送hotfix，當helper.calculateEstimatedHourlyWage(working) 為 undefined時，不要讓workings 有 `estimated_hourly_wage` 這個欄位。
- [ ] 送hotfix，新增DB migration，將 `estimated_hourly_wage` 欄位為null 的資料的`estimated_hourly_wage`欄位移除掉。

To check:
- [ ] 做aggregate操作的時候，如果有的資料該欄位有值，有的資料沒有該欄位，實際上計算數量的時候會不會錯掉。
- [ ] 做aggregate操作的時候，如果全部的資料都沒有該欄位，那該欄位可以用 $exists 判定是否存在嗎？

**Comment by mark86092** [comment]
> 做aggregate操作的時候，如果有的資料該欄位有值，有的資料沒有該欄位，實際上計算數量的時候會不會錯掉。

https://docs.mongodb.com/manual/reference/operator/aggregation/avg/

$avg ignores non-numeric values. If all operands for the average are non-numeric, $avg returns null.

> 做aggregate操作的時候，如果全部的資料都沒有該欄位，那該欄位可以用 $exists 判定是否存在嗎？

以 avg 來說，會是 null，要判斷是否是 null，$exists 可能效果不太一樣

**Comment by LittleWhiteYA** [comment]
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L29
如果把這行的 `{ $exists: true }` 改成 `{ $ne: null }` 會不會更好??
(stackoverflow) 剛好有人問到 [http://stackoverflow.com/questions/4057196/how-do-you-query-this-in-mongo-is-not-null]

**Comment by h091237557** [comment]
#325
