### ISSUE TITLE
研究 Passport 並具體提出我們如何修改架構的方案

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#326]
使用Passport的目的是做好使用者登入的基礎建設。
如果未來有使用者登入、多重帳號綁定的需求，可以順利解決。

未說明清楚的部分請補充。

**Comment by mark86092** [comment]
> 使用Passport的目的是做好使用者登入的基礎建設。

這裡不只有使用者登入，還可以包含登入狀態的維護等等，例如是
1. 使用者的帳密驗證與設定 cookie (session)
2. Token based 的單次登入

所以，這邊我覺得還可以研究 expressjs cookie 與 [session](https://github.com/expressjs/session) 的搭配，還有 [session store](https://github.com/expressjs/session#compatible-session-stores) 的選擇
