### ISSUE TITLE
研究 API documentation 的模板或工具

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#327]
研究是否有現成的API模板或工具，讓我們在撰寫ＡＰＩ文件的時候，能夠有個規則遵循，進而溝通的效率。

未說明清楚的部分請補充。

**Comment by mark86092** [comment]
之前其實有用過 http://apidocjs.com/，code 在此 https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/master/routes/workings.js#L373 (參見 #81 )
