### ISSUE TITLE
取得熱門文章列表的機制 改進

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#328]
這個issue先放入backlog

問題： 目前的面試、工作經驗分享的熱門列表部分，如果有文章讚數非常的多，顯示的列表幾乎永遠保持一樣。對使用者來說會失去新鮮感。

解決方案：
使用 mongodb的 capped collection，固定max collection size，裡面每一筆doc存 `experience_id` `user_id` `action_type` `value` 

`action_type` 可能為 `like`或 `reply`，意即使用者對這篇文章的操作是讚或留言
`value` 是一個數值，代表這個操作對這篇文章熱門程度的加權值。例如讚為1，留言為5 。

要取出熱門文章列表的時候，以`experience_id`把資料分組，計算每一個 `experience_id`的total value，排序後將由價值最大到最小輸出。 

討論點：
1. 熱門文章列表可能是常用的api，是否會對於後端負擔太大？

**Comment by mark86092** [comment]
等 6月中之後，事情告一段落再想這個問題

**Comment by h091237557** [comment]
目前仔細想一下，評分機制目前還是比較好的選擇，而至於 @barry800414 提出的

> 熱門文章列表可能是常用的api，是否會對於後端負擔太大？

我會將運算出的熱門文章，存放在 redis 裡面，並且在存放時會多存一個時間戳，然後每一次使用者呼叫這個 api 時，會先直接去 redis 先將資料取出，然後比對時間戳，如果超果某個時間(待討論)，則會取資料庫重新計算熱門文章，然後在存入 redis ，反正則直接回傳 redis 的熱門文章。

**Comment by h091237557** [comment]
DB spec 
[傳送門](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=258223779024738993976243&h2=%E7%B6%93%E9%A9%97%E7%86%B1%E9%96%80%E8%A8%98%E9%8C%84-Collection-%E8%A8%AD%E8%A8%88)

**Comment by barry800414** [comment]
暫時沒有要改這個，先 close
