### ISSUE TITLE
POST /interview_experiences/ 當前端送 experience_in_year: null 時的判斷

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#351]
目前的前端，`experience_in_year` 在沒填的時後會送null。
`optionalNumber()` 的判定會因為它不是undefined，又不是數字，就return false，導致422 error

可能有兩種選擇：
1. 改前端，沒填的時候這個欄位不要傳
2. 改後端，optionalNumber() 判定時，undefined or null 都視為未填，但這個後端可能在塞資料的時候要注意。

**Comment by mark86092** [comment]
@barry800414 前端版本號是？

目前 master 上應該不會送的

**Comment by mark86092** [comment]
我目前送出去的 https://api-stage-v4.goodjob.life/experiences/5949440c5a24e9000f7fe675 是 experience_in_year 是選填，我沒填的

你對照看看

**Comment by barry800414** [comment]
剛剛 checkout 到master 上，最後一個commit 是 24f6e73005286ed58c2968d9b1f2e22725ed7daa
已經解決了
