### ISSUE TITLE
補充API doc 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#352]
有一些很久以前的API，沒有任何文件。對前端來說不太方便，要補上api doc。
- [ ] 搜尋公司API （for 公司自動完成）
- [ ] 搜尋職稱API （for 職稱自動完成）
- ... 可能還有更多

補在這邊，或是直接用ApiDoc，然後在此頁放讓前端可以run 起 ApiDoc server 的指令
https://github.com/goodjoblife/WorkTimeSurvey-backend/wiki/API-Endpoint-2.x-or-ealier

**Comment by mark86092** [comment]
根據 #353，麻煩檢查現有的是否正確

**Comment by h091237557** [comment]
關於 #353 我看[apdoc的文檔](http://apidocjs.com/#param-api-success)，我還以為只有`apiParam `可以用預設和是否選擇，剛剛試了一下`apiSuccess `好像也可以，我被他文檔虎了， @barry800414  這邊就交給你囉 ~
