### ISSUE TITLE
API 文件維護與工具

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#353]
- [x] 尋找文件產生器（目前有一個候選 http://apidocjs.com）
- [x] 撰寫 API 文件的計畫
- [x] 有 generator，要處理怎麼 generate，與放置產生後的文件（可能會需要 deploy）

API-Doc文件撰寫確認。 #358 
- [x]  GET /experiences
- [x]  GET /experiences/:id
- [x]  POST /work_experiences
- [x]  POST /interview_experiences
- [x]  POST /experiences/:id/replies 
- [x]  GET /experiences/:id/replies 
- [x]  POST /experiences/:id/likes
- [x]  DELETE /experiences/:id/likes
- [x]  POST /replies/:id/likes
- [x]  DELETE /replies/:id/likes

**Comment by h091237557** [comment]
記憶中 
1. 上次開會當時好像就決定要用它了。
2. 當時的計畫是，如果是新的api要建立，因為會需要常變動或討論，所以先寫在dropbox doc，接下來穩定時在用api doc，每當有需要修改時在一個一個補= = 
3. 他是會在某個我們指定的資料夾內產生index.html，但現在我在想的一個問題是，假設我們在dev/4.x產生了這個檔案，然後我們將他丟了gh-pages，最後在github.io可以有api文件。但我現在在想的是有沒有方法，當我們dev/4.x所產生了 index.html 後，就自動的也會更新gh-pages的頁面，不然有可能發生dev/4.x 的doc和gh-pages的doc，不相同的狀況。

**Comment by mark86092** [comment]
1. 好啊
2. 舊的可能要想一下怎麼安排（距離下次修可能有點久
3. 現在應該會有兩個分支 master 與 dev/? 都需要有 doc，我想這邊 ci 可以設定部署到 server 上（我可以支援）

**Comment by h091237557** [comment]
關於第三點問一下，你是指要將api doc 丟到我們的正式機上嗎 ???

**Comment by h091237557** [comment]
#358
