### ISSUE TITLE
Repo 重新命名成 goodjob-api

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#355]
這個 repository 目前已經含有整個 GoodJob 官網＆服務的 API Server

所以原本的名字除了冗長之外，也不好識別用途

我覺得可以改名成 `goodjob-api`

根據 https://help.github.com/articles/renaming-a-repository/ ，
所有的 issue, wiki, pr 與 repo 都會有重新導向

**Comment by mark86092** [comment]
副作用：大家的 git 記得修改 remote

**Comment by h091237557** [comment]
沒啥意件~

**Comment by LittleWhiteYA** [comment]
api-server 感覺很不厲害ㄏㄏ

**Comment by mark86092** [comment]
改成跟內文一樣了 goodjob-api

**Comment by barry800414** [comment]
How about `goodob-backend` ？

**Comment by LittleWhiteYA** [comment]
`GoodJob-*` ? XD
CamelCase 感覺比較順眼哈哈

**Comment by barry800414** [comment]
- [ ] GoodJob-API
- [ ] GoodJob-Backend

來投個票吧！
或是如果要我直接決定的話，我會選 `GoodJob-Backend`

**Comment by mark86092** [comment]
我不想用 backend 的原因：單純覺得講得明確一點是 API 服務，backend 可能有點廣

BTW, 為什麼要特別 `-` ？

**Comment by barry800414** [comment]
全部連在一起比較不好讀，專案名稱主要還是好懂為目的
然後，backend有點廣的意思是？

**Comment by mark86092** [comment]
例如 render 網頁的 server 端 code 也能算後端，提供 contentful 快取的也算後端，我是覺得有點太廣啦

**Comment by mark86092** [comment]
> 全部連在一起比較不好讀

感覺 GoodJobAPI 和 GoodJobShare, WorkTimeSurvey 很像沒這樣的問題耶

而且風格有一致，覺得呢？

**Comment by barry800414** [comment]
`GoodJob-xxx` 當然比 `GoodJobxxx` 好讀，也更凸顯 GoodJob 是一個單位
backend or API 我只覺得 backend比較直覺好懂，覺得沒必要這麼嚴格定義
對其他人來說，這個名稱就只是讓其他人理解它的用而已

但說實話命名我沒有太多意見，你覺得GoodJobAPI 比較好的話，就 GoodJobAPI 吧

**Comment by mark86092** [comment]
看來改名字有點麻煩，維持原名

**Comment by LittleWhiteYA** [comment]
竟然就這樣放棄了XDDDD

**Comment by barry800414** [comment]
我覺得要改耶，現在已經不只是worktime，名字主要是給其他人看的。

`GoodJobAPI` / `GoodJob-Backend` 都可，彥齊給你決定
改改改～

**Comment by mark86092** [comment]
GoodJob-API
