### ISSUE TITLE
面試經驗新增 API QA 的 A 可以是 空字串

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#364]
根據 https://github.com/goodjoblife/GoodJobShare/issues/170 ，當 A 是空字串時，面試經驗新增 API 會出現 validation error

但是根據設計圖，可以只填寫 Q，而不填 A

建議：當 POST 來的 interview_qas[i].answer 是 undefined or ""，都統一轉換成 ""

**Comment by h091237557** [comment]
目前我們是先驗證然後在組資料進db，所以如果`interview_qas[i].answer`為`undefined`，這邊處理ok，
但問題是如果進來的answer是`""`的話，就會直接被answer大小為`1~5000`字數這個防掉。

**Comment by h091237557** [comment]
所以目前有兩個選項
1. 之間讓他被防，因為本來就不合規定。(1~5000)
2. 修改規定，改成(小於5000)

**Comment by mark86092** [comment]
API Change to

interview_qas 的 qa 是由一個 `{ question, answer }` 組成，
其中 question 必填，answer 選填，當 answer 可以是不存在、undefined、null或是 string，是 string 時，限制 >= 1 個字

後端實作：
建議 answer 不存在、undefined、null 時，都不要存這欄位，當是 string 時，限制 >= 一個字

**Comment by h091237557** [comment]
#365

**Comment by mark86092** [comment]
Done
