### ISSUE TITLE
http redirect to https automatically

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#38]
雖然說大部分的人應該會是直接點開連結，不過如果有人真的用打字的，擔心會跑到http底下。是否要自動轉向到https呢?

ref:  http://stackoverflow.com/questions/7450940/automatic-https-connection-redirect-with-node-js-express

**Comment by mark86092** [comment]
你是指哪個網站要 redirect ？

**Comment by barry800414** [comment]
worktime.goodjob.life 這一個~

**Comment by mark86092** [comment]
可以把這個問題轉po到 goodjoblife/WorkTimeSurvey 嘛？
