### ISSUE TITLE
Code-Rule : id 代表的含意規範 

### ISSUE THREAD

**Issue by h091237557** [goodjoblife/WorkTimeSurvey-backend#394]
提案者 : @mark86092 

**Rule :** 
希望無論是任何的層級，看到的 xxxx_id 都定義為 Mongod DB 的 ObjectID.

```
不論任何一層級 (model、route) ，只要是不屬於 mongodb 的 id 命名規則如下 :

const xxxxxx_id_string = "123456789";
const experience_id_string = req.parms.id; 

然後只屬於 mongodb 的 id 則為

const xxxxxxx_id = new ObjectId("123456789");
```
**為啥要降呢 ?**

假設有下面的程式碼 : 

```
reply_like_model.createLike(reply_id,user);
```
你要著麼知道 user 裡的 _id 是 string 還是 ObjectId 呢 ? 但如果是根據上面的規則
你很容易就知道它們一定是指 ObjectId 。

**但這有缺點**
那就是命名有點長，不過之前寫測試有用過，如下 : 

```
 user_experience_id = result.ops[0]._id;
 user_experience_id_string = result.ops[0]._id.toString();
```

**那為啥不是 id 直接當 string 就好 ??**
如果用了這個規則，你要著麼分辦 model 層吐出來的 id 和其它 id 的取別 ?? 
model 吐出來的 id 代表的意思就是 ObjectID 。

**Comment by barry800414** [comment]
`experience_id_by_user = result.ops[0]._id;` 為什麼要有 by_user ??

**Comment by h091237557** [comment]
喔 ~ 那邊我該了，變成 user_experience_id

**Comment by mark86092** [comment]
我們目前是沒辦法規定型別在 code 裡（所以只能靠大家用猜的）

有在做型別的 js 多半要經過轉換才能用，這部分我是沒用過，所以才會有這個 Proposal 作為默認（至少在寫 code 減少大腦轉換）

**Comment by mark86092** [comment]
沒問題的話，未來的就用這個當基準
