### ISSUE TITLE
新API 需求

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#4]
這個是我認為我們的MVP如果可以做到，會最有說服力、讓人最想用的功能。
API spec:
Input: job_title, N
Output:
company_id1, company_name1, average_week_working_time_of_job_title1, num_of_data1
company_id2, company_name2, average_week_working_time_of_job_title2, num_of_data2
...
company_idN, company_nameN, average_week_working_time_of_job_titleN, num_of_dataN

其中，順序是按照該公司的該職缺的平均週工時排，並取出前N個即可。 所以是某間公司的給定職缺的所有平均週工時去做平均，然後排序。

舉例:
input: job_title="軟體工程師", N=3
output:
12345678, 雅虎, 60, 3
22345678, Google, 55, 3
32345678, Microsoft, 50, 10

**Comment by barry800414** [comment]
重新制定API:
input: { "job_title": job_title, "top_n": N }
output: 
[
   //這樣是一家公司的資料
   { "company_id": company_id1, 
     "company_name": company_name1, 
     "week_working_time": [ h1, h2, h3 ... ]
   },
   { "company_id": company_id2, 
     "company_name": company_name2, 
     "week_working_time": [ h1, h2, h3 ... ]
   },
   ...
   { "company_id": company_idN, 
     "company_name": company_nameN, 
     "week_working_time": [ h1, h2, h3 ... ]
   }
]

Note: please return top N company's data only, decided by average week working time per company in descending order.

**Comment by mark86092** [comment]
![image](https://cloud.githubusercontent.com/assets/1908007/16476811/bf333724-3ebd-11e6-8e1c-ecd0541a5087.png)
