### ISSUE TITLE
你可能想看的 API

### ISSUE THREAD

**Issue by LittleWhiteYA** [goodjoblife/WorkTimeSurvey-backend#403]
- [ ] API Doc 先補上
- [ ] API

**Comment by barry800414** [comment]
剛跟彥齊討論了一下，我先做一個利用熱門文章 API 的版本，之後再取代掉。
我會更新 API doc & 直接送ＰＲ

**Comment by barry800414** [comment]
[reference](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=186304060954724831207711&h2=%E5%8F%96%E5%BE%97%E4%BD%A0%E5%8F%AF%E8%83%BD%E4%B9%9F%E6%83%B3%E7%9C%8B%E7%9A%84%E7%B6%93%E9%A9%97%E5%88%86%E4%BA%AB%E5%88%97%E8%A1%A8)

**Comment by barry800414** [comment]
暫時沒有要做這個，先 close
