### ISSUE TITLE
引入 prettier (code formatter)？

### ISSUE THREAD

**Issue by LittleWhiteYA** [goodjoblife/WorkTimeSurvey-backend#425]
https://github.com/prettier/prettier

覺得雖然現在有 eslint
但是 code format 還是得自己做覺得很麻煩=  =...
想要有 formatter 幫統一一些 eslint 模糊的地方
也會長的比較好看

**Comment by LittleWhiteYA** [comment]
@mark86092 @h091237557 @barry800414

**Comment by h091237557** [comment]
好啊

**Comment by mark86092** [comment]
可以呀，不過可以等 dev 進到 master 再來嗎？

現在的 diff 數如果有衝突要修我會很驚悚

**Comment by LittleWhiteYA** [comment]
好哦  讚讚讚
