### ISSUE TITLE
留言狀態

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#428]
- [ ] 存入的時候有預設值 "published"
- [ ] 提供 API 讓 user 修改 (#427)
- [ ] 取出的時候根據狀態 filter

**Comment by barry800414** [comment]
想問一下這三個task，是否已經有人開始做某一部份，我可以協助其他部分。

**Comment by mark86092** [comment]
還是需要開成三個 issue 嗎？有 PR 代號的是已開 PR

**Comment by barry800414** [comment]
不用另開 issue 沒關係，我只是想問是不是有人已經在做了，不要重複做

**Comment by mark86092** [comment]
我開一下成四個好了

**Comment by barry800414** [comment]
`存入的時候有預設值 "published"`
這個我認領喔

**Comment by barry800414** [comment]
ＯＫ

**Comment by h091237557** [comment]
取出的時候根據狀態 filter ，偶來 ~
