### ISSUE TITLE
GET 自己的經驗分享狀態

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#429]
需要回傳 status 欄位

**Comment by h091237557** [comment]
目前有回傳status ，但我api doc 沒加到 QQ
[https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/view_models/get_experiences.js](https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/view_models/get_experiences.js)

**Comment by mark86092** [comment]
那就補個 PR 改文件吧

**Comment by barry800414** [comment]
@h091237557  你要補嗎？  還是我補？

**Comment by h091237557** [comment]
#430

**Comment by h091237557** [comment]
下次如果有想做的 ~ 先看看project裡面的in progress ~
