### ISSUE TITLE
使用者管理資料 experiences 新增時 status 需要有預設值

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#436]
剛發現 POST experiences 的時候，好像沒有預設 status : published

**Comment by mark86092** [comment]
workings 也看一下

**Comment by h091237557** [comment]
https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/387

**Comment by barry800414** [comment]
噢有，寫在 `pickupInterviewExperience` 裡面，沒 trace 到誤會了

跟 reply 設預設值的地方不太一樣，reply 那邊是 reply_model 設定預設值。
我先關掉這個 PR，之後可以討論一下有預設值的部分，是要在 route 處理還是 model 處理。

**Comment by h091237557** [comment]
ok

**Comment by mark86092** [comment]
@barry800414 原則上在 model 層沒問題

experiences 是考慮到上傳時可以指定 status，所以放在 route 層

**Comment by barry800414** [comment]
workings 有設定 status 預設值

**Comment by barry800414** [comment]
`experiences 是考慮到上傳時可以指定 status，所以放在 route 層`

這個是預留未來有其他狀態的時候用的嗎？
因為目前其實不需要讓使用者可以設定 status

**Comment by mark86092** [comment]
> 因為目前其實不需要讓使用者可以設定 status

沒錯，不過當初那個 PR 有根據： @h091237557  `關於1的部份，事實上正常來想，應該是要post時可以代status的參數`

不過這個 API 的嚴謹度我還沒重新看一次

**Comment by mark86092** [comment]
我會再看一次那個 API 決定一下

**Comment by barry800414** [comment]
其實我覺得預留沒問題
未來如果有存在後端的草稿機制，這個就可能會用到

**Comment by mark86092** [comment]
@barry800414 是的，沒錯，不過就是要去看 API 到底允許哪些 status 被傳入，剛剛看是有需要加強的
