### ISSUE TITLE
[使用者編輯自己的資料] 編輯經驗分享 API

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#457]
1. 前端在點擊確定修改時，會將更新的欄位 (or 一個 experience 物件 ) 傳送到後端。
2. 後端收到時，要先驗證使用者。
3. 再來檢查欄位與值是否合法。
4. 將舊的資料取出來，並且存放到 XXXX_collection 中。
5. 更新 experience collection 的資料，並且將 update time 修改成當時。

By Mark @barry800414 

測試案例
1. 作者編輯經驗時，預期成功 (要去抓 experience 看看是否和要更新的相同，已經xxx_collection是否有存入)
2. 使用者編輯不屬於它的經驗，預期失敗 403
3. 未登入時去編輯經驗，預期失敗 401
4. 作者填寫不合法欄位值進行更新，預期失敗 422

**Comment by barry800414** [comment]
reference doc:

[PATCH /interview_experiences/:id](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=697935142979234777512747&h2=修改面試經驗分享-API)

[PATCH /work_experiences/:id](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=711719710807200005290591&h2=修改工作經驗分享-API)

@h091237557  我有更新 API doc 的部分了，PATCH 的部分我本來想說統一用一個 endpoint `PATCH /experiences/:id` 但想想我們 POST 的時候是用兩個 endpoint (`POST /work_experiences/`, `POST /interview_experiences/` ，而 PATCH 的欄位可以到像 POST 一樣多且複雜，覺得還是分兩個比較好

不過這個可以討論，你覺得不妥我們再看怎麼修

**Comment by barry800414** [comment]
另外流程上我再修改一下

1. 前端在點擊確定修改時，會將更新的欄位 (or 一個 experience 物件 ) 傳送到後端。
2. 後端收到時，要先驗證使用者。
3. `將舊的資料取出來，把要更新的欄位更新到該物件，驗證該物件是否符合原本規範`
4. 將舊的資料取出來，並且存放到 XXXX_collection 中，`_id 會變為 ref_id，_id 則是 mongodb 自動產生。`
5. 更新 experience collection 的資料，並且將 `updated_at` 修改成當時。

**Comment by h091237557** [comment]
@barry800414 這種修改多個欄位的用 put 比較適合 API DOC 修改為

PUT /interview_experiences/:id
PUT /work_experiences/:id

**Comment by h091237557** [comment]
應該直接改 `PUT /experiences/:id` or `PUT /me/experiences/:id ` 會比較適合。

**Comment by barry800414** [comment]
ＯＫ，確實，要前端自已檢查是哪些欄位有修改，也是一個工。
不如整份原本的衣料載入介面讓使用者修改後，整份重新上傳，這樣的話用 PUT 比較好。

I prefer:
PUT /me/interview_experiences/:id
PUT /me/work_experiences/:id

因為事實上是修改自己產的內容，而work/interview 我建議分開，開發上比較好處理

Please 直接修改 API doc

**Comment by mark86092** [comment]
我自己會建議在這裡不需要放入 `/me/xxx`，一方面可以跟 POST 蠻對稱的（上傳 post 自己產的內容 vs 修改 PUT），而且 `PUT /work_experiences/:id` 其實也足夠指出要修改的標的了

**Comment by h091237557** [comment]
OK 那這樣的話 api 改為如下 :  

```
PUT /work_experiences/:id

PUT/interview_experiences/:id
```
api doc 我會修修

**Comment by barry800414** [comment]
那薪資工時＆留言的部分我修喔

**Comment by h091237557** [comment]
#460

**Comment by barry800414** [comment]
短時間之內不會做這個，先關掉。
