### ISSUE TITLE
[使用者編輯自己的資料] 編輯薪資工時 API

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#459]
[PUT /workings/:id api doc](https://paper.dropbox.com/doc/API-985f9KpSP0l58emwisP8e#:uid=590212812661528067671277&h2=修改工時薪資--API)

[DB doc](https://paper.dropbox.com/doc/3BG8oZX3fOQqZ6gA8s5Hy#:uid=313200593245838924987663&h2=薪資及工時資訊-編輯歷史-Collection-設計)

流程簡介：
1. 前端在點擊確定修改時，會將所有有填寫的欄位傳送到後端，假設叫 A。
2. 後端收到時，要先驗證使用者。
3. 驗證 A 物件是否符合 `POST /workings` 規範
4. 將舊的資料取出來，並且存放到 XXXX_collection 中，_id 會變為 ref_id，_id 則是 mongodb 自動產生。
5. 更新 experience collection 的資料，並且將 updated_at 修改成當時。

**Comment by LittleWhiteYA** [comment]
如果改動舊版的 API，前端不會有問題嗎？

**Comment by barry800414** [comment]
@LittleWhiteYA  route 改了，改成用 PUT 
修改內容系列的全部改成 PUT 了，所有欄位選填必填 同 `POST /workings`

**Comment by barry800414** [comment]
短時間之內不會做這個，先關掉。
