### ISSUE TITLE
職業別薪資工時大調查 Campaign 所需之 API 修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#476]
#### 新增參數欄位
Field | Type | Allowed Value | Explanation
-- | -- | -- | --
campaign_name | String |   | campaign name (e.g. software_engineer)
about_this_job | String |   | 關於此份工作（職場甘苦談）
extra_info | Array | |  額外的資訊 （e.g. [ { key: "ptt", value:  "barry800414" }] ）

### `GET /workings/campaigns/:campaign_name` 
說明：大調查資料表格頁專用的 API，以取得薪資工時資料。若有給定 job_titles，會取得 `job_titles 陣列內有出的 job_title` 的資料，以及`該 compaign 的資料`。  之所以多加 job_titles，就是想避免一開始表格都是空的，讓人沒有太多動機去留。

注意：這邊不會根據公司或職稱去 group，就是一筆一筆顯示。

Field | Type | Allowed Value | Explanation
-- | -- | -- | -- 
sorted_by | String | "created_at" (default) , "week_work_time", "estimated_hourly_wage" | 單筆資料排序的方式
order | String | "descending" (default) , "ascending" | 資料排序由大到小或由小到大。無資料者會被排到最下方
page | String | 非負整數 (default: 0) | 分頁號碼
limit | String | "0 < limit <= 50" (default: 25)  | 單頁資料筆數
job_titles | Array | | 搜尋的職稱陣列

#### 新增 response 欄位
Field | Type | Possible value | Explanation
-- | -- | -- | --
time_and_salary[i].about_this_job | string |  | 關於此份工作

**Comment by mark86092** [comment]
1. `POST /workings`

不懂 `extra_info` 用 array 然後再用 key,value ？用 object 應該就可

允許的 campaign_name 清單要放在哪？應該要做一個允許的白名單，不能任意值

資料庫欄位這裡沒看到，不過應該要建 index

2. `GET /workings/campaigns/:campaign_name`

API 想呈現的是什麼？單看 input 不知道想幹嘛
BTW, GET 有 Array 確定 express 可以 resolve 正確？

**Comment by barry800414** [comment]
> 1.1 不懂 extra_info 用 array 然後再用 key,value ？用 object 應該就可

其實我也是想用 object ，不過 @LittleWhiteYA 說 array better。請 @LittleWhiteYA  說明一下好了

> 1.2 允許的 campaign_name 清單要放在哪？應該要做一個允許的白名單，不能任意值

我覺得不用耶，如果真的有人無聊去打 API，再加個白名單吧

> 1.3 資料庫欄位這裡沒看到，不過應該要建 index

DB 欄位和 index 我再補

**Comment by barry800414** [comment]
> API 想呈現的是什麼？單看 input 不知道想幹嘛

說明我補到原本的內容裡面了

**Comment by LittleWhiteYA** [comment]
> 1.1 不懂 extra_info 用 array 然後再用 key,value ？用 object 應該就可

主要是這個 extra_info 是個以後會常拿來行銷的東西
這次需要的是 ptt 帳號
之後有可能會是 google 帳號之類的
存成 array 的彈性比較好我覺得

**Comment by mark86092** [comment]
@barry800414 

> BTW, GET 有 Array 確定 express 可以 resolve 正確？

這個有確認過？

**Comment by barry800414** [comment]
彥齊我週四晚上回，人還在韓國

**Comment by barry800414** [comment]
@mark86092  @LittleWhiteYA  

確認可以哦！ 這邊是前後端的 sample code：

前端：
https://github.com/barry800414/GoodJobShare/commit/a35ed5e67a5cde04497a55581ff8dad202887009

後端：
https://github.com/barry800414/WorkTimeSurvey-backend/commit/54a8774b6c88a15a21d180edad168077ae0ea7f7

`qs` 這個套件可以幫我們處理好 array 轉成 query string，後端也可以拿到沒有問題！

@peteranny 我也 tag 你一下，前端打 request 的時候可以參考

**Comment by LittleWhiteYA** [comment]
@barry800414 
`GET /workings/campaigns/:campaign_name`
的欄位 sorted_by 打錯了，應該是 sort_by？
