### ISSUE TITLE
[WIP] 管理資料 API & DB 修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#478]
## APIs
- [ ] 1. 新增 `PATCH /workings/:id`

Field | Type | Allowed Value | Explanation
-- | -- | -- | --
status * | String | `admin_archive` |  代表由 GoodJob 管理者審核後封存
reason * | String |  |  封存之原因

須 `admin` 權限

- [ ] 2.  新增 `PATCH /experiences/:id`

Field | Type | Allowed Value | Explanation
-- | -- | -- | --
status * | String | `admin_archive` |  代表由 GoodJob 管理者審核後封存
reason * | String |  |  封存之原因

須 `admin` 權限

- [ ] 3. 修改 `GET /workings/`
功能不變，單純會把 status = `admin_archive` 的薪資工時排除掉。

- [ ] 4. 修改 `GET /experiences/`
功能不變，單純會把 status = `admin_archive` 的薪資工時排除掉。

- [ ] 5. 修改 `GET /experiences/:id`
若該篇經驗分享 status = `admin_archive` ，回傳 404 Not found Error

- [ ] 6. 修改 `GET /me/permissions/search`
要排除 status = `admin_archive` & `hidden` 的資料

- [ ] 7. 修改 `GET /me/experiences`

- [ ] 8. 修改 `GET /me/workings`

## DB design
collection: `users`
新增欄位 role，若該欄位存在且 role = 'admin' ，才有 `admin` 權限

**Comment by mark86092** [comment]
這個 issue 要做的東西我覺得可以拆成幾小包以及順序來看（從功能面，不是從 API 面）

1. workings / experiences 要加上第三個 status (`archive`)
    * 一般 GET 只能傳出 `status=publish` 的 doc （應該不用修）
    * PATCH 只接受 `status=hidden` <--> `status=publish` 互換
    * 權限、數量的部分只計算有效 `status=publish` 的 doc （應該不用修）

2. Migrate `users` collection，增加 role 欄位
    * TODO: 確認 role 欄位是可選或是必要，如果必要，相關的 function 要加上

3. admin 身份相關的 API
    * 擴充 `PATCH` API 的權限判斷時，要小心處理
    * 建議加上 admin 版本的 GET List API

上面三個點可以一個一個完成，也比較好估計時間

另外

Field `reason` 這邊有點奇怪，在 API 裡面是必要，但沒說明在 DB 裏要怎麼放？

我覺得 `reason` 放在 `workings/experiences` 裏是有點突兀，可以討論看看怎麼放比較好

**Comment by barry800414** [comment]
其實我還在整理要改哪些部份中，感謝 @mark86092 的整理！
我再把這些內容整理回主要的說明。
