### ISSUE TITLE
TimeAndSalary的極端資料與一般資料有重疊

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey-backend#481]
當`sort_by=week_work_time&order=descending`，極端資料的最後一筆與一般資料的第一筆，皆為`_id=57a1ca1a1bb8d2030073982e`的資料。

極端資料API: https://api.goodjob.life/workings/extreme?sort_by=week_work_time&order=descending
![2018-04-12 1 24 40](https://user-images.githubusercontent.com/7566586/38632817-6a77048e-3df0-11e8-9cb5-1ef6f6bb522b.png)

一般資料API:https://api.goodjob.life/workings?sort_by=week_work_time&order=descending&page=&limit=25&skip=true
![2018-04-12 1 24 23](https://user-images.githubusercontent.com/7566586/38632815-68bc8c68-3df0-11e8-89d4-273770fd5853.png)

**Comment by mark86092** [comment]
See https://github.com/goodjoblife/GoodJobShare/issues/439, thanks @peteranny
