### ISSUE TITLE
mailing services 選擇

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#507]
### mailgun

1. 每月 10,000 封內免費，接著每 1 USD / 2000 封  
2. 單純 transactional email ，沒有 for 行銷用途的介面
3. [pricing 說明](https://www.mailgun.com/pricing-simple)

### mandrill 
1. 20 USD / 25,000 封信，每月沒用完會 expire
2. 單純 transactional email ，如果是要給行銷用的，要用 mailchimp 
3. [pricing 說明](https://mandrill.com/pricing/)

### AWS SES
1. 每月 62,000 封以前免費，62,000 以後 0.1 USD / 1000 封    
2. 也是單純 transactional email service
3. [pricing 說明](https://aws.amazon.com/tw/ses/pricing/)

### 討論：
1. 專用 IP 位址重要嗎？
2. 其他注意事項？

**Comment by LittleWhiteYA** [comment]
我個人覺得剛開使用可以挑有免費額度的
等信件多到需要付費再重啟討論就好

**Comment by mark86092** [comment]
比較要注意的是，發出去的 email，理論上不太能寄回來，除非我們有 MX

**Comment by barry800414** [comment]
以方案來說，我們應該就是選 AWS SES 的服務了，一個月有 62000 封很夠用。
開 issue 主要是想確認是否有其他的需求

**Comment by barry800414** [comment]
選擇 AWS SES service
