### ISSUE TITLE
登入/驗證流程

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#510]
登入流程：

1. 前端透過 FB SDK 登入
2. 前端取得 access_token 與後端 (`/auth/facebook`) 交換 Token (Sign JWT)
3. 前端儲存 Token 進 Storage，以後的 Token 都透過 Header 驗證

驗證流程：

1. 前端透過 Header 傳送 Token
2. 後端驗證 Token (Verify JWT)

Action Item:

1. Sign JWT Token @ `/auth/facebook` 的 Endpoint
2. Verify JWT Token @ every auth Middleware

Ref: https://github.com/goodjoblife/GoodJobShare/issues/586

**Comment by barry800414** [comment]
@mark86092 這個 issue 已經完成了？

**Comment by mark86092** [comment]
Yes, Done
