### ISSUE TITLE
以公司/職稱查詢薪資、工時 API 換 GraphQL

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#518]
### UI 示意
- [以公司搜尋薪資工時結果頁](https://o2geqq.axshare.com/#g=1&p=%E6%9F%A5%E8%A9%A2%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E7%B5%90%E6%9E%9C%E9%A0%81) 
- [單一公司薪資工時頁](https://o2geqq.axshare.com/#g=1&p=%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E9%A0%81)
- [單一職業薪資工時頁](https://o2geqq.axshare.com/#g=1&p=%E8%81%B7%E6%A5%AD%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E9%A0%81)

### GraphQL Schema Draft
```graphql
scalar Date

type Company {
    id: String!
    name: String!

    // 關聯資訊
    // page為分頁編號，從0開始，limit 為每頁資料數
    salary_work_times(page: Int, limit: Int): [SalaryWorkTime!]!  

    "統計資訊"
    salary_work_time_statistics: SalaryWorkTimeStatistics!
}

type JobTitle {
    name: String!

    // 關聯資訊
    // page為分頁編號，從0開始，limit 為每頁資料數
    salary_work_times(page: Int, limit: Int): [SalaryWorkTime!]!

    "統計資訊"
    salary_work_time_statistics: SalaryWorkTimeStatistics!
}

type Query {      
    "搜尋公司 (會搜尋名稱為 *query* 的公司 ）"
    search_companies(query: String!): [Company!]!
    "取得單間公司（name 與公司名稱需完全符合）"
    company(name: String!): Company!
      
    "取得職稱列表（會搜尋名稱為 *query* 職稱）"
    search_job_titles(query: String!): [JobTitle!]!
    "取得職稱（query 與職稱僅需完全符合）"
    job_title(name: String!): JobTitle!
}
    
type SalaryWorkTime {
    id: ID
    company: Company!
    job_title: JobTitle!
    day_promised_work_time: Int
    day_real_work_time: Int
    email: String // 這是什麼？
    gender: Gender // 這是什麼？
    employment_type: EmploymentType!
    experience_in_year: Int!
    has_compensatory_dayoff: YesNoOrUnknown
    has_overtime_salary: YesNoOrUnknown
    is_overtime_salary_legal: YesNoOrUnknown
    overtime_frequency: Int
    salary: Salary
    sector: String
    week_work_time: Int
    created_at: Date!
    data_time: YearMonth!
    estimated_hourly_wage: Float
}

type SalaryWorkTimeStatistics {
    count: Int!
    average_week_work_time: Number
    has_compensatory_dayoff_count: YesNoOrUnknownCount
    has_overtime_salary_count: YesNoOrUnknownCount
    is_overtime_salary_legal_count: YesNoOrUnknownCount
}
        
type YearMonth {
      year: Int!
      month: Int!
}
    
type Salary {
      type: SalaryType
      amount: Int
}
    
type YesNoOrUnknownCount {
      yes: Int!
      no: Int!
      unknown: Int!
}
    
enum SearchBy {
      COMPANY
      JOB_TITLE
}
    
enum SortBy {
      CREATED_AT
      WEEK_WORK_TIME
      ESTIMATED_HOURLY_WAGE
}
    
enum Order {
      DESCENDING
      ASCENDING
}
    
enum Education {
      大學
      碩士
      博士
      高職
      五專
      二專
      二技
      高中
      國中
      國小
}

enum SalaryType {
      year
      month
      day
      hour
}

enum YesNoOrUnknown {
      yes
      no
      "don't know"
}

enum EmploymentType {
      full_time
      part_time
      intern
      temporary
      contract
      dispatched_labor
}
```

- [Full version of GraphQL draft is here](https://paper.dropbox.com/doc/2.0---AWZSsGCwx7xF468_rrd0Gng4Ag-FMUrXf2FFd9e8JHx0UBis#:uid=794838097360151126934552&h2=GraphQL-Schema)

### Deprecated API
- `GET /search_by/company/group_by/company`
- `GET /search_by/job_title/group_by/company`

**Comment by LittleWhiteYA** [comment]
@barry800414 這邊問幾個問題

### 第一個問題
```
      // 取得公司列表 (query 與公司名稱僅需前面的字串符合）
      companies(query: String!): [Company!]!
```
這隻 query 對應到的頁面是 [以公司搜尋薪資工時結果頁](https://o2geqq.axshare.com/#g=1&p=%E6%9F%A5%E8%A9%A2%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E5%B7%A5%E6%99%82%E7%B5%90%E6%9E%9C%E9%A0%81)

這樣看起來回傳的資訊應該只要有
1. 模糊搜尋到的公司名稱
2. 根據模糊搜尋到的公司名稱做統計有幾筆資料

所以感覺不用像 company 一樣回傳其他的欄位

### 第二個問題

如果使用者看到上面那個頁面後，因為點下去會打第 2 個 query
```
      // 取得公司（query 與公司名稱僅需完全符合）
      company(query: String!): Company!
```
這樣 "聯發科技" 應該找不到任何資料吧？
因為第 2 個 query 是完全比對了
所以只有點 "聯發科技股份有限公司" 才會有資料，這樣不是很怪嗎？

**Comment by barry800414** [comment]
第一個問題

> 所以感覺不用像 company 一樣回傳其他的欄位

company 裡面需要什麼欄位，就是下 query 時讓前端決定囉！ 這個不就是 graphql 的好處～？


第二個問題

目前我們 production 上面的資料，確實有不少筆薪資工時資料的 company.name 是 `聯發科技` 哦。所以用完全比對是會有資料的

p.s. 這個是未來要優化的地方，把 `聯發科技` 
`聯發科` 都換成 `聯發科技股份有限公司`

**Comment by LittleWhiteYA** [comment]
> company 這個物件裡面需要什麼欄位，就是下 query 時讓前端決定囉！ 這個不就是 graphql 的好處～？

這是 graphql 的彈性沒錯
但是現在看起來不需要的東西在設計上就不該回傳
companies 這 query 看起來只需要 SalaryWorkTimeWithMetaData 這個 type 的東西
而 company 這 query 則不需要 SalaryWorkTimeWithMetaData
companies 要的是統計過後的資料
而 company 要的則是某間公司的資料
這 2 個 query 名字上會讓我有種 companies 是 company 的複數版

第二個問題看起來是沒問題了

**Comment by mark86092** [comment]
續小白說的，我覺的

type Query {      
      companies(query: String!): [Company!]!
}

這塊名稱有點混淆，或許直接取名成 `search_company` / `search_companies` 比較直覺，
又或者，這個 query 的本體是 SalaryWorktime (salary_worktime 的 camel case)

那就可以取名成：
```
search_salary_worktime_xxx: [SearchResult!]!

type SearchResult {
    company
    salary_worktimes
    salary_worktimes_statics
}
```

**Comment by mark86092** [comment]
小白的第二個問題，乍看之下真的以為是 query，但實際上是完全等於，不如用 `company(name: String)` ?

**Comment by barry800414** [comment]
當時在想 schema 是從物理意義上下去想的，而不是用 restful API 下去想的

所以 companies 是 company 的複數沒錯（就是 company 的陣列）

如果用 restful API 的思維，確實兩支 api 要的資料不同，搜尋結果的那支api 只需要資料數，不該回傳個別 company 的資料

但 graphql 下去想的思維是，搜尋結果就是回傳 company 物件，裡面要什麼欄位就自己挑來用。 未來如果搜尋結果頁真的需要個別公司的資料，就不用再重寫了。

**Comment by mark86092** [comment]
是說這邊我想知道：在寫 Reslover 時，

```
SalaryWorkTimeWithMetaData: {
    async data(root, args, ctx) {
    }
}
```

的 root 會長什麼樣子呀？

感覺抓不太到拆成這麼多層，中間的 root 應該長怎麼

**Comment by mark86092** [comment]
另外，有個問題，是用 salary_worktime (SalaryWorktime) 還是 salary_work_time (SalaryWorkTime) 哪個？這邊兩種都有

**Comment by barry800414** [comment]
@mark86092 

> root 會長什麼樣子呀？

看起來要是一個物件，包含 type（=`job_title` or `company`) & query (=job_title 的字串 或 company 名稱的字串）

```
{
    type: 'job_title',
    query: '軟體工程師'
}
```

**Comment by barry800414** [comment]
> 另外，有個問題，是用 salary_worktime (SalaryWorktime) 還是 salary_work_time (SalaryWorkTime) 哪個？這邊兩種都有

我全部改成 `salary_work_time` (SalaryWorkTime） 了

**Comment by LittleWhiteYA** [comment]
我其實不是很能理解 query, mutation name 用 snake_case
但是 type 用 camelCase 分成 2 種的用意...

> 但 graphql 下去想的思維是，搜尋結果就是回傳 company 物件，裡面要什麼欄位就自己挑來用。 未來如果搜尋結果頁真的需要個別公司的資料，就不用再重寫了。

我不認為這跟 graphql 或 restful 有關係
API 可以多給很多東西沒錯
但 companies 跟 company 這 2 隻 API 的用途很明顯不一樣
我覺得換個名字會比較清楚

**Comment by mark86092** [comment]
(1)

```gql
type Query {
    search_salary_work_time_by_company(query: String!): [CompanySearchResult!]!
}

type CompanySearchResult {
    salary_work_times: [SalaryWorkTime!]!
    statics ...
}
```

(2)

```gql
type Query {
    search_companies(query: String!): [Company!]!
}

type Company {
    salary_work_times: [SalaryWorkTime!]!
    salary_work_time_statics ...
}
```

**Comment by LittleWhiteYA** [comment]
```
type Query {
  companiesMetaData (name: String!): [CompanyMetaData!]!
  company(name: String!): companyPayload!
}

type CompanyMetaData {
  name: String!
  count: Int!
  company: [Company!]!
}

type companyPayload {
  statistics: SalaryWorkTimeStatistics
  company: [Company!]!
}
```

**Comment by mark86092** [comment]
```js
resolvers = {
  companyPayload: {
    company(obj, args, ctx) {
    }
  }
}
```

**Comment by mark86092** [comment]
```
type Query {
  search_companies(name: String!): [MetaCompany!]!
}

type MetaCompany {
  SalaryWorkTimeStatistics!
  ...Company
}

type companyPayload {
  salary_work_time_statistics: SalaryWorkTimeStatistics!
  ...Company
}
```

**Comment by barry800414** [comment]
```graphql
type Query {      
      // 取得公司列表 (query 與公司名稱僅需前面的字串符合）
      search_companies(query: String!): [CompanySearchResult!]!
      // 取得公司（query 與公司名稱僅需完全符合）
      company(query: String!): Company!
}

type CompanySearchResult {
   salary_work_time_statistics: SalaryWorkTimeStatistics!
   company: Company!
}
```

**Comment by LittleWhiteYA** [comment]
```gql
type MetaCompany implements Company {

}

type Company {
  a:
  b:
}
```

**Comment by mark86092** [comment]
```gql
type Company {
    name: String!
    salary_work_times: [SalaryWorkTime!]!

    "統計資訊"
    salary_work_time_statistics: SalaryWorkTimeStatistics!
}
```

**Comment by mark86092** [comment]
```gql
type Reply {
   # experience_id: ID!
   experence: Experience
}
```

**Comment by barry800414** [comment]
@LittleWhiteYA  想問預計完成的時間～

**Comment by LittleWhiteYA** [comment]
再等等
有些地方以前寫不太對要改

**Comment by barry800414** [comment]
@LittleWhiteYA  如果你已經有寫一部分，可以把 code 推上來
因為我這邊也會送 schema 的 PR，你有寫我就 base on 你的去寫就好

然後，我這邊還是會需要抓時程，所以還是要麻煩你估一個送 PR 的時間給我喔～

**Comment by barry800414** [comment]
修正一下，薪資工時資料沒有 region 這個欄位（經驗分享才有），是 sector 純字串。
已更新 schema

**Comment by barry800414** [comment]
@LittleWhiteYA  小白 #528 merge 了
我想確認 以職稱搜尋薪資工時的部分你會做對不對？

另外有幾個新的需求：
1. `search_companies` & `search_job_titles` 的部分需要分頁，這個部分是 @peteranny  反映的，職稱如果打工程師會有一堆結果，可能會導致頁面 render 延遲
2. Company 裡面的 `salary_work_times` 排序，以職稱排序
3. JobTitle 裡面的 `salary_work_times` 排序，以公司名稱排序

**Comment by LittleWhiteYA** [comment]
對   新的需求等上面做完
確定沒問題再說吧

**Comment by barry800414** [comment]
@LittleWhiteYA  
我今天有跟 @mark86092  討論，覺得 graphql 的 API 要根據這些資訊排序，然後做分頁，可能不是那麼好做。所以暫時先決定不做，交給前端去排序＆分頁，也就是維持現在的狀況。

**Comment by mark86092** [comment]
我把 checklist 整理如下：

Query Resolver
- [x] search_companies (#528)
- [ ] company
- [ ] search_job_titles
- [ ] job_title

**Comment by mark86092** [comment]
剩下 Query.company 還沒實作
