### ISSUE TITLE
驗證Email 相關API Spec

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/WorkTimeSurvey-backend#531]
## [POST] /me/verifyEmail
用途：觸發發送驗證信

### header
Authorization Header

### parameters
| field | type | allowed value | explanation | 
| --- | --- | --- | --- |
| email | string | | 使用者的信箱 |
| redirectURL | string | | 驗證成功後，按鈕會導向的 URL | 
| redirectTarget | string | `experience`, `time-and-salary`, `labor-rights`, null | 驗證成功後想要導向的內容種類。這個欄位的目的，是讓前端決定要用哪個文案樣板去顯示驗證成功的資訊。 |

範例

```
    {
    	"email": string,
    	"redirectURL": string,
    	"redirectTarget": null | "experience" | "time-and-salary" | "labor-rights"
    }
```

### response

沿用原本一般的成功與失敗template 即可，不需要額外資訊

## [POST] /users/verifyEmail
用途：信件點開的頁面進入後，用來驗證信箱的 API

### parameters
| field | type | allowed value | explanation | 
| --- | --- | --- | --- |
| token | string | | 驗證 token |

範例

```
    {
    	"token": string
    }
```

### response
| field | type | allowed value | explanation | 
| --- | --- | --- | --- |
| accessToken | string | | 後端發給前端作為身份驗證用的 token |
| redirectURL | string | | 驗證成功後，按鈕會導向的 URL。是當初從 [POST] /me/verifyEmail 傳進去的參數。 |
| redirectTarget | string | `experience`, `time-and-salary`, `labor-rights`, null | 驗證成功後想要導向的內容種類。這個欄位的目的，是讓前端決定要用哪個文案樣板去顯示驗證成功的資訊。是當初從 [POST] /me/verifyEmail 傳進去的參數。  |

範例
```
    {
    	"accessToken": string,
    	"redirectURL": string,
    	"redirectTarget": null | "experience" | "time-and-salary" | "labor-rights"
    }
```

## GraphQL Schema 更新
```graphql
    Query {
      me {
        id: String!
        email: String
        emailStatus: UNVERIFIED | SENT_VERIFICATION_LINK | VERIFIED
        createdAt: Date!
      }
    }
```

**Comment by barry800414** [comment]
> emailStatus: UNVERIFIED | SENT_VERIFICATION_LINK | VERIFIED

只有這個欄位要怎麼知道驗證信已過期？

**Comment by barry800414** [comment]
這邊補充說明一下實作細節

## [POST] /me/verifyEmail
這邊會拿 user._id + user.email + redirectUrl + redirectTarget + expireTime 去做加密，作為 token 發送到指定信箱

## [POST] /users/verifyEmail
這邊會拿 token 去解密得到 user._id + user.email + redirectUrl + redirectTarget + expireTime，檢查是否過期，user._id 是否存在、user.email 是否正確，如果都通過，更新 user.emailStatus，並且簽發登入用的 accessToken ，連同 redirectUrl + redirectTarget 一併回傳

**Comment by mark86092** [comment]
`[POST] /me/verifyEmail`

補充：這邊應該要帶 Authorization Header, user 不會有 email (從 post 送入了)

**Comment by mark86092** [comment]
>> emailStatus: UNVERIFIED | SENT_VERIFICATION_LINK | VERIFIED
> 只有這個欄位要怎麼知道驗證信已過期？

除非要記曾經送過 Email 在 DB，不然應該無法得知？

**Comment by WendellLiu** [comment]
對client 來說過期應該就相當於UNVERIFIED ，除非過期會需要相對應的UI 。

**Comment by WendellLiu** [comment]
> `[POST] /me/verifyEmail`
> 
> 補充：這邊應該要帶 Authorization Header, user 不會有 email (從 post 送入了)

@mark86092 
這我不太懂，要帶authorization header 我懂了，不過這支API 應該就是要請user 輸入email ?

**Comment by mark86092** [comment]
是繼韋銘補充說的，他寫 user.email，但這裡就是從post輸入，不是user的屬性

**Comment by WendellLiu** [comment]
@mark86092 
懂了，沒看到上面的補充 ＸＤ

**Comment by barry800414** [comment]
假如 email 驗證信過期，什麼時間點會去更新 user.emailStatus = `UNVERIFIED` 呢？

**Comment by WendellLiu** [comment]
定義上是過期的那個時間點。實作可以再想想

**Comment by mark86092** [comment]
```
Init -------> UNVERIFIED -----寄出驗證信---> SENT_VERIFICATION_LINK
                     |                                |
                     \<------ 驗證失敗-----------------+
                                                      |
                                                    驗證成功
                                                      |
                                                      |
                                                  VERIFIED
```

**Comment by mark86092** [comment]
目前看起來 email api 的生命週期是這樣，

是說，驗證失敗 / 驗證碼過期 變成 UNVERIFIED 的理由是什麼？

多個驗證碼又要怎麼定義，例如，

user 的 A 驗證碼過期，但 B 還沒過期，使用者是 UNVERIFIED 還是 SENT_VERIFICATION_LINK？

**Comment by mark86092** [comment]
我是覺得實際上這樣應該夠：

```
Init -------> UNVERIFIED -----寄出驗證信---> SENT_VERIFICATION_LINK
                                                      |
                              驗證失敗-----------------+
                                                      |
                                                    驗證成功
                                                      |
                                                      |
                                                  VERIFIED
```

**Comment by barry800414** [comment]
@mark86092  @WendellLiu 
剛仔細想了一下，其實好像也不需要把 emailStatus 改回 `UNVERIFIED`

emailStatus = `SENT_VERIFICATION_LINK` 的時候這樣顯示：https://zpl.io/b6jB7Nm
emailStatus = `UNVERIFIED` 的時候這樣顯示：https://zpl.io/V0Rp19w

所以晏成你提的規格應該是ＯＫ的，也就是彥齊這個留言 https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/531#issuecomment-469122613 畫的流程

**Comment by WendellLiu** [comment]
改回去這件事情應該是因為當時有討論到如果超過一定時間會有不同反應。不過確實既然top bar 其實只是wording 不同但都是重新寄信，那可能可以維持這樣單純就好（也就是無視寄出多久的條件）。

**Comment by mark86092** [comment]
> 當時有討論到如果超過一定時間會有不同反應

這個牽涉到要儲存寄信的時間點，同時還要考慮使用者有要求多封驗證信的問題，
如果未來要這樣做，那要好好想想流程會怎麼跑，要怎麼實作

**Comment by WendellLiu** [comment]
嗯嗯，我本來只是開介面啦，但的確可以先考慮一下可行性。

**Comment by barry800414** [comment]
我覺得可以先不用把事情想得太複雜，先做最簡單可行的版本就好

**Comment by mark86092** [comment]
> 如果未來要這樣做

只好 quota 自己說的，future work ^^，不會做的意思

**Comment by barry800414** [comment]
這個 issue 如果沒有問題的話，實作的部分可以交給 @mark86092  你嗎？

**Comment by mark86092** [comment]
@barry800414 @WendellLiu  是說可以用 Mutation 實作嗎？這樣比較簡單 xD

**Comment by WendellLiu** [comment]
@mark86092 
應該可呦

**Comment by LittleWhiteYA** [comment]
emailStatus: UNVERIFIED | SENT_VERIFICATION_LINK | VERIFIED

會需要記那麼多狀態的理由為何？
我們會用到嗎0.0

**Comment by mark86092** [comment]
https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/531#issuecomment-469122613 上面提到的，應該3個不算多，前端也需要顯示不同狀態

**Comment by barry800414** [comment]
> emailStatus: UNVERIFIED | SENT_VERIFICATION_LINK | VERIFIED
會需要記那麼多狀態的理由為何？
我們會用到嗎0.0

前端介面的顯示上需要，請參考
https://zpl.io/V0Rp19w
https://zpl.io/b6jB7Nm

**Comment by mark86092** [comment]
@barry800414  https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/531#issuecomment-473506671 https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/531#issuecomment-473506706

Kindly remind
