### ISSUE TITLE
JobTitle 欄位有問題

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#535]
Bug in #528

![image](https://user-images.githubusercontent.com/1908007/53804146-aa2e4180-3f81-11e9-9328-48960373595b.png)

SalaryWorkTime 的 JobTitle type 對不起來 (String --> type JobTitle)

**Comment by LittleWhiteYA** [comment]
看不太懂你的意思

**Comment by mark86092** [comment]
我打這個 graphql 出現問題

```gql
{
  search_companies(query: "聯發科") {
    name
    salary_work_times {
      id
      job_title {
        name
      }
    }
  }
}
```

**Comment by LittleWhiteYA** [comment]
這是 job_title 的部份還沒寫完的關係

**Comment by mark86092** [comment]
Fixed
