### ISSUE TITLE
salary_work_time_count沒有回傳數量

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey-backend#566]
```
{
  salary_work_time_count
}
```

會有error `Cannot return null for non-nullable field Query.salary_work_time_count.`
還是我query下錯？

Curl: 
```
curl 'https://api-dev.goodjob.life/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://api-dev.goodjob.life' --data-binary '{"query":"{\n  salary_work_time_count\n}\n"}' --compressed
```

**Comment by mark86092** [comment]
你看哪裡的 schema 看到的？

**Comment by peteranny** [comment]
https://api-dev.goodjob.life/graphql

**Comment by LittleWhiteYA** [comment]
有看到這 Query，但是沒實做 resolver
不確定當時為何要加0.0

@barry800414 
https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/541

**Comment by peteranny** [comment]
我在query的時候會需要拿salary_work_times總數
如果不用salary_work_times_count那麼我有其他方法拿嗎?

**Comment by mark86092** [comment]
後端要補，還沒實做

**Comment by barry800414** [comment]
有人在做這個嗎？  沒有的話我來補一下這個

**Comment by mark86092** [comment]
@barry800414  
![image](https://user-images.githubusercontent.com/1908007/57090108-9d875900-6d38-11e9-8e38-4eeffb96873a.png)

可以稍微看一下 assign，有時候不會即時看留言

**Comment by barry800414** [comment]
好的，其實我有看到，想說確認一下
