### ISSUE TITLE
Sentry error:  null is not an object (evaluating 'r.node.getBoundingClientRect')

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#573]
這個 error 也吃了大量 quota ，需要解決掉它比較好
猜測是小教室頁用到的某個套件出錯
https://sentry.io/share/issue/ec8c42e772514b80aa1584bd5ebca41d/

**Comment by mark86092** [comment]
這個是小教室旁邊的浮動框，在手機視窗下是隱藏，所以出錯

**Comment by barry800414** [comment]
赫然發現我根本開錯 repo ...

**Comment by mark86092** [comment]
其實有提供 Transfer issue 功能啦
