### ISSUE TITLE
使用 email template

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#578]
目前 email template 放在這邊：
https://github.com/goodjoblife/email-template

還沒有確定應該要如何使用
想問 @wutingy 有沒有可能讓它變成一個 js 檔，裡面就是一個 function ，讓我可以傳變數進去，然後回傳 html string 給我

**Comment by wutingy** [comment]
可以改成 function，雖然我覺得正統好像不是這樣做，但事先這樣比較快

**Comment by mark86092** [comment]
不知道 @barry800414 本來是打算怎麼整合？然後 heml QPS 多高？（call 一次 function 如果花 50ms，其實很可怕，CPU bounded 的）

**Comment by wutingy** [comment]
應該是不會用到 heml，因為那只是我工作的原始檔案，會直接用產出的 html 做

**Comment by barry800414** [comment]
> 不知道 @barry800414 本來是打算怎麼整合？

原本想的就是我上面寫的，一個 js 檔可以 import ，裡面有個 function，把變數帶進去，回傳 html string，然後我就可以寄出了

> 可以改成 function，雖然我覺得正統好像不是這樣做，但事先這樣比較快

@wutingy  你那邊有更推薦的做法嗎？

**Comment by wutingy** [comment]
沒有～因為這段不是我負責的

**Comment by barry800414** [comment]
我打算複製貼上成 js 

剛測試了一下，可以成功寄出
不過，想問一下圖片出不來是正常的嗎？

<img width="778" alt="螢幕快照 2019-05-19 上午9 21 23" src="https://user-images.githubusercontent.com/3805975/57976648-9f7b3880-7a17-11e9-950a-aeddb2a34ba3.png">

**Comment by wutingy** [comment]
圖片原本是使用 base64 嵌入，我用 html 看是正常，如果顯示不出來，可以取代成圖片檔案，但是要麻煩上傳到 s3 產生連結

**Comment by wutingy** [comment]
![gj-email-logo](https://user-images.githubusercontent.com/8353239/57977446-75cc0c80-7a2b-11e9-8e14-962041e2c5e9.png)
