### ISSUE TITLE
實習經驗單篇讀取不出來

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#588]
https://www.goodjob.life/experiences/5ad0ed48e06216e31489b5cd

<img width="319" alt="螢幕快照 2019-06-11 下午10 25 51" src="https://user-images.githubusercontent.com/3805975/59280290-eadfda00-8c97-11e9-8160-5c93ce4e3aad.png">
初步研判是 graphql API 出錯

**Comment by LittleWhiteYA** [comment]
看起來是 graphql 的問題
幫找找 MongoDB 裡面的這筆資料

**Comment by barry800414** [comment]
剛看 graphql 這塊完全沒做ＸＤ，所以應該壞一陣子了
我剛把實習資料的欄位用 slack 給你了！
