### ISSUE TITLE
graphql type 解析出錯

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#590]
https://www.goodjob.life/experiences/5c3d3f2f1e004a00108d92bf

<img width="455" alt="螢幕快照 2019-06-18 下午6 30 43" src="https://user-images.githubusercontent.com/3805975/59675121-36920680-91f7-11e9-8202-18ae42c1714f.png">

會造成頁面無法正常 render 

另外發現這樣的錯誤，似乎不會送 sentry

**Comment by mark86092** [comment]
要看前端是不是把所有的 api error 都接走了（我猜是）

這個欄位是不是本來就該是 int ?

**Comment by mark86092** [comment]
確認了，這個欄位允許 Float
