### ISSUE TITLE
任務清單

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#669]
每一個任務需要有

1. 觸發條件
2. 完成條件
3. 點數

需要討論的可以開 issue / 或開會 / slack

**Ouptut: 一份文件**

這個是開發 Worker 的 function 需要實做的商業邏輯

參見：https://paper.dropbox.com/doc/--AtgorjEFYv5XMIx2bAyHU_x0Ag-u3IWUZ7Klx3fMQrk0WKfV#:h2=%E4%BB%BB%E5%8B%99%E6%B8%85%E5%96%AE

**Comment by mark86092** [comment]
可能的任務

- 註冊
- 分享薪資工時
- 分享面試經驗
- 分享工作心得
- 看廣告
- 分享網站到 facebook

**Comment by barry800414** [comment]
@mark86092  所以是這個 issue ，我需要補什麼資訊嗎？

**Comment by barry800414** [comment]
我把這個 issue 的內容移到 #672  了，這個關閉
