### ISSUE TITLE
[1] 新增欄位 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#67]
1. 廠區/門市/分公司:
field_name: <code>sector</code>
value: string 

2. 加班是否有加班費: 
field name: <code>has_overtime_salary</code>
value = <code>{"yes", "no", "don't know"} </code>

3. 加班費是否違反勞基法:
field name: <code>overtime_salary_is_legal</code>
value = <code>{ "yes", "no", "don't know" }</code>

4. 是否有補修:
field name:  <code>has_compensatory_dayoff</code>
value = <code>{ "yes", "no", "don't know" } </code>

以上都有可能是空值，因為是選填

related PR: #70

**Comment by mark86092** [comment]
我建議修改一些欄位：

```
is_overtime_salary_legal: "yes", "no", "don't know"
has_compensatory_dayoff: "yes", "no"
```

加班有無補修 目前我只看到兩個欄位

**Comment by barry800414** [comment]
這個要跟Tin確認一下，我看會議紀錄是有這個欄位

**Comment by mark86092** [comment]
再麻煩確認，我是看網頁的

**Comment by barry800414** [comment]
是否有補修:
field name: has_compensatory_dayoff
value = { "yes", "no", "don't know" } 

確認是這樣沒錯
