### ISSUE TITLE
如何驗證有分享到 FB

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#673]

**Comment by barry800414** [comment]
前端的部分，facebook 的 SDK 有提供一個 callback，如果使用者真的有分享，會被執行

reference：https://developers.facebook.com/docs/javascript/reference/FB.ui?locale=zh_TW
https://stackoverflow.com/questions/23116001/facebook-like-and-share-button-with-callback

後端的部分，我覺得可以有一支 API ，被呼叫的時候，就觸發完成任務的 event 
（覺得可以不用做驗證，也就是工程師如果懂怎麼打 API ，也是可以人工觸發）
