### ISSUE TITLE
Salary 型別討論

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#681]
目前 Salary 的 amount 是 int

```
type Salary {
  amount: Int!
}
```

但是：
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/src/schema/salary_work_time.js#L291

https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/680/files#diff-0f021964042186307993ce83e5a9d062R9

https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/dev/src/schema/experience.js#L380

其實都允許 Salary.amount 是 Float

看是否要改成 Float 或是 API 的 Output 用另外的型別(Salary的平均有小數很正常)。

**Comment by LittleWhiteYA** [comment]
我覺得輸入限制用 Int 好像比較合理
可以再開個 type 是 averageSalary 之類的

**Comment by barry800414** [comment]
同意 @LittleWhiteYA

**Comment by mark86092** [comment]
那就維持 Int，averageSalary 用新的 Type
