### ISSUE TITLE
統一編號 到 組織或公司名稱對應問題

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#7]
目前我們有的資料是 公司登記&營業登記的資料，可以從統一編號查該單位名稱。
但有幾個問題:

1.我們沒有非營利組織、政府部門、醫院、學校等等的統一編號資料
2.目前所擁有的資料的問題是，同一個單位名稱可能對到多個統一編號，意思就是有很多同名的公司或商業登記。  狀況如下:
#unique_id -> #unique_name
company: 662007 -> 661595
business: 682453 -> 604033

目前的解決方案:
1. 有統編看統編
2. 沒統編，查名字:
   a.對到多個id，不理他，id直接當null
   b.對到一個，好棒棒，直接用id
   c.對到0個，自己建一個

**Comment by mark86092** [comment]
剩下插入公司資料還沒處理
