### ISSUE TITLE
[權限機制] user. permissionExpiresAt field & migration

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#706]
針對 collection `users` ，新增欄位 `permissionExpiresAt` ，type 為 Date 

### Tasks 
- [x] Mongoose model 上加上 `permissionExpiresAt` 欄位，default 值為 user created 的時間
- [x] 寫一個 migration，針對目前有全站權限的使用者，將 `user.permissionExpiresAt` 更新至 migration 當下 + N 分鐘後（N 待決定）

#### 附註說明
這邊有全站權限的使用者指的是：
- 至少有一筆 salary_work_time 資料，且 `status = "publish" & "archive.is_archived" = false`    or
- 至少有一筆 experience 資料，且 `status = "publish" & "archive.is_archived" = false`  

#### reference doc 
https://paper.dropbox.com/doc/Spec---AuRP0DQYZPc8z1x8_2BiB_vFAg-yTjTZKtjFgIGR4BzQKvpA

**Comment by mark86092** [comment]
> 寫一個 migration，針對目前有全站權限的使用者，將 user.permissionExpiresAt 更新至 migration 當下 + N 分鐘後（N 待決定）

想問這個的目的是什麼？

**Comment by barry800414** [comment]
> 想問這個的目的是什麼？

讓原本有留資料的使用者，可以有一段比較長的時間是有權限的
（畢竟原本是留一筆可以看全部終身）

**Comment by mark86092** [comment]
看 PR 的指的一段比較長的時間，所以是指 migration 當下往後數，而不是使用者剛登入才開始計算時間？
