### ISSUE TITLE
googleLogin unauthorized returns 200 rather than 401

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey-backend#710]
前端使用API打mutation googleLogin若回傳unauthorized的回應碼是200而不是401，這是預期的嗎？

**Comment by barry800414** [comment]
目前我的理解是 grapqhl 不會有除了 200 / 500 以外的 status code 
https://stackoverflow.com/questions/42937502/graphql-how-to-respond-with-different-status-code

確切的請 @mark86092  @LittleWhiteYA  補充了

**Comment by mark86092** [comment]
Graphql 要看是不是有 errors，而不是 status code

https://www.apollographql.com/docs/apollo-server/data/errors/

主要是因為 Graphql 含有很多的 Resolver，所以他會針對每個單一 resolvers 給出錯誤

**Comment by mark86092** [comment]
官方給出的 spec https://graphql.org/learn/serving-over-http/#response

與 Output 範例如圖：

![image](https://user-images.githubusercontent.com/1908007/74640276-3b55f280-51aa-11ea-94bc-0d3e82345c8f.png)

**Comment by barry800414** [comment]
目前我實驗的結論是：
- 後端整個掛 -> 500
- input type 不符合 graphql schema  -> 400
- 其他情況，都是 200

如果有其他 case ，可以再補充喔
我先把這個 issue 關起來了
