### ISSUE TITLE
[cronjob] 背景 Job 會更新 PaymentRecord Status

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#770]
需要注意的條件：

1. 背景 Job 每 N 分鐘跑一次去 Tappay 檢查 PaymentRecord Status (N = 5)
2. 當上一輪還沒跑完，不該跑新的一輪
3. 需要有 logging 機制知道更新了什麼，抓了什麼

**Comment by mark86092** [comment]
For 2., k8s cronjob 提供 concurrency 控制機制，

> Forbid: The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run

https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
