### ISSUE TITLE
更新 PaymentRecord

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#816]
query.paymentRecord 的時候，需要將 init 的 paymentRecord 從 tappay 更新

**Comment by barry800414** [comment]
Hi @mark86092 
Are you working on it already ? 

I started to work on it, but I found that you assigned to yourself

**Comment by barry800414** [comment]
My work in progress branch 
https://github.com/goodjoblife/WorkTimeSurvey-backend/tree/feature/816

**Comment by mark86092** [comment]
TODO:

- [ ] State machine
- [ ] Testing

**Comment by barry800414** [comment]
@LittleWhiteYA 

### TODO

When calling `query.paymentRecord`
- [ ] to have a state machine to transit `subscription` status based on `paymentRecord` status & result from tappay, otherwise subscription status will keep `init` forever. 
- [ ] add unit testing

**Comment by barry800414** [comment]
@LittleWhiteYA Work in Progress branch :
https://github.com/goodjoblife/WorkTimeSurvey-backend/compare/dev...feature/816-2

**Comment by barry800414** [comment]
done by https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/830
