### ISSUE TITLE
時間相關欄位取用出現問題

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/WorkTimeSurvey-backend#824]
```graphql
{
  paymentRecord(id: "63e502e843dde500125595d6") {
    id
    status
    createdAt
    subscription {
      createdAt
    }
  }
}
```
message: `Cannot return null for non-nullable field Subscription.createdAt.`

same as other fields, `paymentRecord.subscription.createdAt`, `paymentRecord.paymentMethodSnapshot.createdAt`, `paymentRecord.updatedAt`

**Comment by mark86092** [comment]
@WendellLiu 新產生的 paymentRecord 或其他資料應該都有 createdAt, updatedAt 了
