### ISSUE TITLE
預期錯誤的卡號會發生runtime error

### ISSUE THREAD

**Issue by WendellLiu** [goodjoblife/WorkTimeSurvey-backend#827]
reference: https://docs.tappaysdk.com/tutorial/zh/reference.html#test-card

case1: `4242 4222 0418 4242` - Bank System Error
case2: `4242 4216 0218 4242` - Card Error

client side error: `GraphqlError: GraphqlError: Cannot read properties of undefined (reading 'card_key')`

**Comment by mark86092** [comment]
Tappay 已知有兩種錯誤：

```json
{
  "status": 10005,
  "msg": "Bank system error",
  "bank_result_code": "10005"
}
```

或

```json
{
  "status": 10003,
  "msg": "Card error, please ask for issuer",
  "bank_result_code": "10003"
}
```

不管是 Bank System Error 或是 Card Error，或是不預期的錯誤，後端會一律回底下的回答

```json
{
  "errors": [
    "message": "Transaction fail"
  ]
}
```
