### ISSUE TITLE
API 開放 cors 讓 client 可以存取

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey-backend#85]
As title,

we need to survey which domains we need to open.

**Comment by barry800414** [comment]
ref: https://github.com/abalone0204/Clairvoyance/blob/master/chromeExtension/manifest.json

**Comment by barry800414** [comment]
@mark86092  我想問一下，我們要所有的後端都對求職天眼通所需的網域開cors，還是只有求職天眼通的API對求職天眼通所需的網域開cors?

**Comment by mark86092** [comment]
> 只有求職天眼通的API對求職天眼通所需的網域開cors

這個就好

**Comment by barry800414** [comment]
有點不知道為什麼這樣不work
https://github.com/goodjoblife/WorkTimeSurvey-backend/blob/clairvoyance-cors/app.js#L51

**Comment by mark86092** [comment]
你如何測試它？

**Comment by barry800414** [comment]
1. <code> router.get('/by-company',` function(req, res, next) {  </code>  
    裡面加入console.log("in by company");
2. `MONGODB_URI="mongodb://localhost/test" npm start`
3. 打開瀏覽器打:  http://localhost:3000/clairvoyance/search/by-company?company=%E8%81%AF%E7%99%BC%E7%A7%91
4. 看terminal 有沒有訊息，結果有訊息  (原本應該要是沒有?
