### ISSUE TITLE
fail to buy by production key

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey-backend#883]
https://www-dev.goodjob.life/buy/result/649ad0c90d10970013968a3e

<img width="1440" alt="Screenshot 2023-06-27 at 8 07 29 PM" src="https://github.com/goodjoblife/WorkTimeSurvey-backend/assets/3805975/16b51635-bec8-4b3e-9729-40909ee89ed7">

**Comment by mark86092** [comment]
Fixed
